"use client";
/* Protected media is served by authenticated API routes, so Next image optimization is intentionally bypassed. */
/* eslint-disable @next/next/no-img-element */

import { useActionFeedback } from "@/components/action-modal-provider";
import { useLocale } from "@/components/locale-provider";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import { Archive, BookOpenText, Building2, Camera, CheckCircle2, Download, FileArchive, FileLock2, FileText, FolderHeart, Hourglass, Image as ImageIcon, Landmark, LoaderCircle, LockKeyhole, MoreHorizontal, PackageOpen, Pencil, Plus, ScrollText, ShieldCheck, Timer, Trash2, Upload, Users, X } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import type { ArchiveCollection, ArchiveFile, ArchiveMemory, ArchivePayload, ArchiveStory, FamilyAsset, TimeCapsule, VaultDocument } from "@/lib/archive-types";

type Kind = "collection" | "story" | "asset" | "capsule";
type EditableArchiveRecord = ArchiveCollection | ArchiveStory | FamilyAsset | TimeCapsule;
type Form = Record<string, string>;
const date = new Intl.DateTimeFormat("bn-BD", { dateStyle: "medium" });
const dateTime = new Intl.DateTimeFormat("bn-BD", { dateStyle: "medium", timeStyle: "short" });
const money = new Intl.NumberFormat("bn-BD", { style: "currency", currency: "BDT", maximumFractionDigits: 0 });
const today = () => new Date().toISOString().slice(0, 10);
const futureLocal = () => { const value = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000); value.setMinutes(value.getMinutes() - value.getTimezoneOffset()); return value.toISOString().slice(0, 16); };
const n = (value: number | string | null | undefined) => Number(value ?? 0) || 0;
const titles: Record<Kind, string> = { collection: "নতুন archive collection", story: "পারিবারিক ইতিহাস লিখুন", asset: "Family asset যোগ করুন", capsule: "Time capsule তৈরি করুন" };
const assetLabels: Record<string, string> = { land: "Land", house: "House", flat: "Flat", vehicle: "Vehicle", business: "Business", investment: "Investment", jewelry: "Jewelry", other: "Other" };

function initial(kind: Kind): Form {
  if (kind === "collection") return { collectionType: "album", visibility: "family", coverColor: "#153A5B" };
  if (kind === "story") return { storyDate: today(), visibility: "family" };
  if (kind === "asset") return { assetType: "land", estimatedValue: "0", visibility: "admins", acquisitionDate: today() };
  return { unlockAt: futureLocal(), visibility: "family" };
}

export function ArchiveCenter() {
  const { locale, pick } = useLocale();
  const [family, setFamily] = useState<ArchivePayload["family"]>();
  const [collections, setCollections] = useState<ArchiveCollection[]>([]);
  const [memories, setMemories] = useState<ArchiveMemory[]>([]);
  const [stories, setStories] = useState<ArchiveStory[]>([]);
  const [documents, setDocuments] = useState<VaultDocument[]>([]);
  const [assets, setAssets] = useState<FamilyAsset[]>([]);
  const [capsules, setCapsules] = useState<TimeCapsule[]>([]);
  const [files, setFiles] = useState<ArchiveFile[]>([]);
  const [canManage, setCanManage] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [migrationRequired, setMigrationRequired] = useState(false);
  const [setupRequired, setSetupRequired] = useState(false);
  const [feedback, setFeedback] = useActionFeedback();
  const [kind, setKind] = useState<Kind | null>(null);
  const [editingRecord, setEditingRecord] = useState<{ id: string; kind: Kind } | null>(null);
  const [form, setForm] = useState<Form>({});
  const [uploadMode, setUploadMode] = useState<"memory" | "vault" | null>(null);
  const [uploadForm, setUploadForm] = useState<Form>({ visibility: "family", category: "other", memoryDate: today() });
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [now] = useState(Date.now);

  const load = useCallback(async () => {
    try {
      const response = await fetch("/api/archives", { cache: "no-store" }), payload = await response.json() as ArchivePayload;
      if (payload.code === "FAMILY_SETUP_REQUIRED") { setSetupRequired(true); return; }
      if (!response.ok) throw new Error(payload.error ?? pick("ফ্যামিলি আর্কাইভ লোড হয়নি।", "Could not load Family Archives."));
      setFamily(payload.family); setCollections(payload.collections ?? []); setMemories(payload.memories ?? []); setStories(payload.stories ?? []); setDocuments(payload.documents ?? []); setAssets(payload.assets ?? []); setCapsules(payload.capsules ?? []); setFiles(payload.files ?? []); setCanManage(Boolean(payload.permissions?.canManage)); setMigrationRequired(Boolean(payload.migrationRequired)); setSetupRequired(false);
    } catch (error) { setFeedback(error instanceof Error ? error.message : pick("ফ্যামিলি আর্কাইভ লোড হয়নি।", "Could not load Family Archives.")); }
    finally { setLoading(false); }
  }, [pick, setFeedback]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);

  const activeCollections = collections.filter((item) => item.status === "active");
  const publishedStories = stories.filter((item) => item.status === "published");
  const expiringDocuments = documents.filter((item) => item.expiry_date && new Date(item.expiry_date).getTime() > now && new Date(item.expiry_date).getTime() < now + 90 * 86400000);
  const assetValue = assets.filter((item) => item.status === "active").reduce((sum, item) => sum + n(item.estimated_value), 0);
  const lockedCapsules = capsules.filter((item) => !item.is_unlocked);
  const fileFor = (entityType: "memory" | "vault_document", id: string) => files.find((item) => item.entity_type === entityType && item.entity_id === id);
  const collectionName = (id: string) => collections.find((item) => item.id === id)?.name ?? "Collection";

  function openCreate(next: Kind) { setEditingRecord(null); setKind(next); setForm(initial(next)); }
  function openEdit(next: Kind, item: EditableArchiveRecord) { const value = item as unknown as Record<string, unknown>; const forms: Record<Kind, Form> = {
    collection: { name: String(value.name ?? ""), description: String(value.description ?? ""), collectionType: String(value.collection_type ?? "album"), coverColor: String(value.cover_color ?? "#153A5B"), visibility: String(value.visibility ?? "family") },
    story: { title: String(value.title ?? ""), content: String(value.content ?? ""), storyDate: String(value.story_date ?? ""), storyteller: String(value.storyteller ?? ""), peopleTags: Array.isArray(value.people_tags) ? value.people_tags.join(", ") : "", place: String(value.place ?? ""), visibility: String(value.visibility ?? "family") },
    asset: { title: String(value.title ?? ""), assetType: String(value.asset_type ?? "other"), ownership: String(value.ownership ?? ""), location: String(value.location ?? ""), identifierMasked: String(value.identifier_masked ?? ""), acquisitionDate: String(value.acquisition_date ?? ""), estimatedValue: String(value.estimated_value ?? 0), notes: String(value.notes ?? ""), visibility: String(value.visibility ?? "admins") },
    capsule: { title: String(value.title ?? ""), message: String(value.message ?? ""), recipientNames: String(value.recipient_names ?? ""), unlockAt: value.unlock_at ? new Date(String(value.unlock_at)).toISOString().slice(0, 16) : futureLocal(), visibility: String(value.visibility ?? "family") },
  }; setEditingRecord({ id: item.id, kind: next }); setKind(next); setForm(forms[next]); }
  async function action(name: string, data: Record<string, unknown>) { const response = await fetch("/api/archives/records", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: name, data }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Record save হয়নি।"); }
  async function create() { if (!kind) return; setSaving(true); try { if (editingRecord) { const response = await fetch("/api/archives/records", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, recordId: editingRecord.id, data: form }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? pick("রেকর্ড আপডেট হয়নি।", "The record could not be updated.")); } else await action(`create_${kind}`, form); setKind(null); setEditingRecord(null); await load(); setFeedback(pick(`${titles[kind]} ${editingRecord ? "আপডেট" : "সেভ"} হয়েছে।`, `Archive record was ${editingRecord ? "updated" : "saved"}.`)); } catch (error) { setFeedback(error instanceof Error ? error.message : pick("রেকর্ড সেভ হয়নি।", "The record could not be saved.")); } finally { setSaving(false); } }
  async function remove(recordKind: Kind, recordId: string) { setSaving(true); try { const response = await fetch("/api/archives/records", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: recordKind, recordId }) }); const payload = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(payload.error ?? "Delete হয়নি।"); await load(); setFeedback(payload.message ?? "Record delete হয়েছে।"); } catch (error) { setFeedback(error instanceof Error ? error.message : "Delete হয়নি।"); } finally { setSaving(false); } }
  async function updateStatus(entity: string, id: string, status: string) { setSaving(true); try { await action("update_status", { entity, id, status }); await load(); setFeedback(pick(`অবস্থা ${status} হয়েছে।`, `Status changed to ${status}.`)); } catch (error) { setFeedback(error instanceof Error ? error.message : pick("অবস্থা আপডেট হয়নি।", "Status update failed.")); } finally { setSaving(false); } }
  function openUpload(mode: "memory" | "vault") { setUploadMode(mode); setUploadFile(null); setUploadForm(mode === "memory" ? { visibility: "family", memoryDate: today(), collectionId: activeCollections[0]?.id ?? "" } : { visibility: "private", category: "other" }); }
  async function upload() { if (!uploadMode || !uploadFile) return; const body = new FormData(); body.set("mode", uploadMode); body.set("file", uploadFile); Object.entries(uploadForm).forEach(([key, value]) => body.set(key, value)); setSaving(true); try { const response = await fetch("/api/archives/upload", { method: "POST", body }), payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? pick("আপলোড হয়নি।", "Upload failed.")); setUploadMode(null); setUploadFile(null); await load(); setFeedback(uploadMode === "memory" ? pick("স্মৃতি আর্কাইভে সেভ হয়েছে।", "Memory saved to the archive.") : pick("ডকুমেন্ট সিকিউর ভল্টে সেভ হয়েছে।", "Document saved to the secure vault.")); } catch (error) { setFeedback(error instanceof Error ? error.message : pick("আপলোড হয়নি।", "Upload failed.")); } finally { setSaving(false); } }
  async function deleteFile(id: string) { setSaving(true); try { const response = await fetch(`/api/archive-file/${id}`, { method: "DELETE" }); const payload = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(payload.error ?? "File delete হয়নি।"); await load(); setFeedback(payload.message ?? "File delete হয়েছে।"); } catch (error) { setFeedback(error instanceof Error ? error.message : "File delete হয়নি।"); } finally { setSaving(false); } }

  async function exportXlsx() {
    setExporting(true); try {
      const XLSX = await import("xlsx"), workbook = XLSX.utils.book_new(); const add = (bn: string, en: string, rows: Array<Record<string, unknown>>) => XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), locale === "bn" ? bn : en);
      add("সংগ্রহ", "Collections", collections.map((item) => ({ [pick("সংগ্রহ", "Collection")]: item.name, [pick("ধরন", "Type")]: item.collection_type, [pick("গোপনীয়তা", "Visibility")]: item.visibility, [pick("অবস্থা", "Status")]: item.status, [pick("তৈরিকারী", "Creator")]: item.created_by_name, [pick("বিবরণ", "Description")]: item.description ?? "" })));
      add("স্মৃতি", "Memories", memories.map((item) => ({ [pick("সংগ্রহ", "Collection")]: collectionName(item.collection_id), [pick("শিরোনাম", "Title")]: item.title, [pick("ধরন", "Type")]: item.memory_type, [pick("তারিখ", "Date")]: item.memory_date ?? "", [pick("স্থান", "Place")]: item.place ?? "", [pick("ব্যক্তিবর্গ", "People")]: item.people_tags.join(", "), [pick("গোপনীয়তা", "Visibility")]: item.visibility, [pick("আপলোডকারী", "Uploader")]: item.uploaded_by_name, [pick("বিবরণ", "Description")]: item.description ?? "" })));
      add("ঐতিহ্যের গল্প", "Heritage Stories", stories.map((item) => ({ [pick("শিরোনাম", "Title")]: item.title, [pick("তারিখ", "Date")]: item.story_date ?? "", [pick("কথক", "Storyteller")]: item.storyteller ?? "", [pick("স্থান", "Place")]: item.place ?? "", [pick("ব্যক্তিবর্গ", "People")]: item.people_tags.join(", "), [pick("অবস্থা", "Status")]: item.status, [pick("গোপনীয়তা", "Visibility")]: item.visibility, [pick("লেখক", "Author")]: item.author_name, [pick("গল্প", "Story")]: item.content })));
      add("ভল্ট সূচি", "Vault Index", documents.map((item) => ({ [pick("শিরোনাম", "Title")]: item.title, [pick("শ্রেণি", "Category")]: item.category, [pick("মালিক", "Owner")]: item.owner_name ?? "", [pick("মাস্ক নম্বর", "Masked number")]: item.document_number_masked ?? "", [pick("ইস্যুকারী", "Issuer")]: item.issuer ?? "", [pick("ইস্যুর তারিখ", "Issue")]: item.issue_date ?? "", [pick("মেয়াদ", "Expiry")]: item.expiry_date ?? "", [pick("গোপনীয়তা", "Visibility")]: item.visibility, [pick("আপলোডকারী", "Uploader")]: item.uploaded_by_name, [pick("নোট", "Notes")]: item.notes ?? "" })));
      add("সম্পদ", "Assets", assets.map((item) => ({ [pick("সম্পদ", "Asset")]: item.title, [pick("ধরন", "Type")]: item.asset_type, [pick("মালিকানা", "Ownership")]: item.ownership ?? "", [pick("স্থান", "Location")]: item.location ?? "", [pick("পরিচিতি", "Identifier")]: item.identifier_masked ?? "", [pick("অর্জনের তারিখ", "Acquired")]: item.acquisition_date ?? "", [pick("মূল্য", "Value")]: n(item.estimated_value), [pick("গোপনীয়তা", "Visibility")]: item.visibility, [pick("অবস্থা", "Status")]: item.status, [pick("নোট", "Notes")]: item.notes ?? "" })));
      add("টাইম ক্যাপসুল", "Time Capsules", capsules.map((item) => ({ [pick("শিরোনাম", "Title")]: item.title, [pick("প্রাপক", "Recipients")]: item.recipient_names ?? "", [pick("খোলার সময়", "Unlock")]: item.unlock_at, [pick("গোপনীয়তা", "Visibility")]: item.visibility, [pick("অবস্থা", "Status")]: item.status, [pick("তৈরিকারী", "Creator")]: item.created_by_name, [pick("বার্তা", "Message")]: item.is_unlocked ? item.message ?? "" : pick("লক করা", "LOCKED") })));
      add("ফাইল সূচি", "File Index", files.map((item) => ({ [pick("রেকর্ড", "Entity")]: item.entity_type, [pick("রেকর্ড আইডি", "Entity ID")]: item.entity_id, [pick("ফাইল", "File")]: item.file_name, [pick("ধরন", "Type")]: item.mime_type, [pick("আকার", "Size")]: item.file_size, [pick("গোপনীয়তা", "Visibility")]: item.visibility, [pick("আপলোডকারী", "Uploader")]: item.uploaded_by_name, [pick("তারিখ", "Date")]: item.created_at })));
      XLSX.writeFile(workbook, `${family?.name_en?.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "family"}-archives-vault.xlsx`);
    } finally { setExporting(false); }
  }

  useEffect(() => {
    const modelContext = (document as Document & { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext; if (!modelContext?.registerTool) return; const lifecycle = new AbortController();
    void Promise.resolve(modelContext.registerTool({ name: "get_family_archive_summary", title: "Get family archive summary", description: "Read a privacy-safe summary of visible collections, memories, published stories, vault expiry reminders and time capsules. Locked capsule messages are never returned.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute(input: unknown) { if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input as object).length) throw new Error("No input fields are accepted."); return { collections: activeCollections.length, memories: memories.length, publishedStories: publishedStories.length, vaultDocuments: documents.length, expiringDocuments: expiringDocuments.map((item) => ({ title: item.title, expiryDate: item.expiry_date })), activeAssets: assets.filter((item) => item.status === "active").length, lockedCapsules: lockedCapsules.map((item) => ({ title: item.title, unlockAt: item.unlock_at })) }; } }, { signal: lifecycle.signal })).catch(() => undefined); return () => lifecycle.abort();
  }, [activeCollections.length, assets, documents.length, expiringDocuments, lockedCapsules, memories.length, publishedStories.length]);

  if (loading) return <main className="grid min-h-[calc(100vh-4rem)] place-items-center"><LoaderCircle className="size-7 animate-spin text-primary" /></main>;
  if (setupRequired) return <main className="mx-auto max-w-3xl p-6 md:p-10"><Empty icon={<Users />} title="Family access সক্রিয় নয়" text="Join code দিয়ে আবেদন করুন। Admin approval-এর পর Family Archives ব্যবহার করা যাবে।" action={<Button asChild className="rounded-xl"><a href="/setup">Family onboarding</a></Button>} /></main>;

  return <main className="mx-auto w-full max-w-[1550px] space-y-5 px-4 py-5 md:px-7 md:py-7">
    <section className="overflow-hidden rounded-3xl bg-[linear-gradient(125deg,#3b245f_0%,#164e63_52%,#8a4b18_100%)] p-5 text-white shadow-xl md:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div className="max-w-2xl"><div className="flex items-center gap-2 text-sm text-violet-100"><ShieldCheck className="size-4" /> {pick("ব্যক্তিগত ঐতিহ্য ও ডকুমেন্ট আর্কাইভ", "Private heritage & document archive")}</div><h1 className="mt-2 text-2xl font-bold tracking-tight md:text-4xl">{pick("ফ্যামিলি আর্কাইভ ও সিকিউর ভল্ট", "Family Archives & Secure Vault")}</h1><p className="mt-2 text-sm leading-6 text-white/75">{pick("স্মৃতি, ছবি, ইতিহাস, গুরুত্বপূর্ণ ডকুমেন্ট, সম্পত্তির রেকর্ড ও ভবিষ্যতের টাইম ক্যাপসুল নিরাপদে সংরক্ষণ করুন।", "Securely preserve memories, photos, history, important documents, property records and future time capsules.")}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" className="rounded-xl" onClick={() => void exportXlsx()} disabled={exporting}>{exporting ? <LoaderCircle className="size-4 animate-spin" /> : <Download className="size-4" />} {pick("সব XLSX", "Export all XLSX")}</Button><Button variant="secondary" className="rounded-xl" onClick={() => openUpload("vault")} disabled={migrationRequired}><FileLock2 className="size-4" /> {pick("ভল্ট আপলোড", "Vault upload")}</Button><Button className="rounded-xl bg-violet-500 text-white hover:bg-violet-600" onClick={() => openUpload("memory")} disabled={!activeCollections.length || migrationRequired}><Upload className="size-4" /> {pick("স্মৃতি আপলোড", "Memory upload")}</Button></div></div></section>
    {migrationRequired ? <div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-800 dark:bg-amber-950/35 dark:text-amber-100">Supabase SQL Editor-এ <b>supabase/migrations/20260927_family_archives_vault.sql</b> চালালে Archives ও Vault data সক্রিয় হবে।</div> : null}
    {feedback ? <div className="flex items-start justify-between gap-3 rounded-2xl border bg-card px-4 py-3 text-sm"><span>{feedback}</span><Button size="icon-xs" variant="ghost" onClick={() => setFeedback(null)}><X /></Button></div> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<ImageIcon />} label={pick("সংরক্ষিত স্মৃতি", "Saved memories")} value={String(memories.length)} note={pick(`${activeCollections.length}টি সক্রিয় সংগ্রহ`, `${activeCollections.length} active collections`)} tone="violet" /><Metric icon={<BookOpenText />} label={pick("প্রকাশিত ইতিহাস", "Published history")} value={String(publishedStories.length)} note={pick(`${stories.filter((item) => item.status === "pending").length}টি পর্যালোচনাধীন`, `${stories.filter((item) => item.status === "pending").length} pending review`)} tone="cyan" /><Metric icon={<FileLock2 />} label={pick("ভল্ট ডকুমেন্ট", "Vault documents")} value={String(documents.length)} note={pick(`${expiringDocuments.length}টির মেয়াদ ৯০ দিনের মধ্যে`, `${expiringDocuments.length} expire within 90 days`)} tone="amber" /><Metric icon={<Landmark />} label={pick("সম্পদ রেজিস্টার", "Asset register")} value={money.format(assetValue)} note={pick(`${assets.filter((item) => item.status === "active").length}টি সক্রিয় সম্পদ`, `${assets.filter((item) => item.status === "active").length} active assets`)} tone="emerald" /></section>

    <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><Card className="rounded-3xl shadow-none"><CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle>Archive collections</CardTitle><p className="mt-1 text-sm text-muted-foreground">Albums, heritage themes এবং protected groups</p></div>{canManage ? <Button className="rounded-xl" onClick={() => openCreate("collection")} disabled={migrationRequired}><Plus /> Collection</Button> : null}</CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{collections.map((collection) => <article key={collection.id} className="overflow-hidden rounded-2xl border"><div className="h-2" style={{ backgroundColor: collection.cover_color }} /><div className="p-4"><div className="flex items-start justify-between gap-2"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><FolderHeart className="size-5" /></span><div className="flex gap-1"><Badge variant="outline">{collection.visibility}</Badge>{canManage ? <Menu disabled={saving} items={[...(collection.status === "active" ? [["Archive", () => void updateStatus("collection", collection.id, "archived")]] as Array<[string, () => void]> : [["Activate", () => void updateStatus("collection", collection.id, "active")]] as Array<[string, () => void]>), ["Edit details", () => openEdit("collection", collection)], ...(memories.some((item) => item.collection_id === collection.id) ? [] : [["Delete permanently", () => void remove("collection", collection.id)]] as Array<[string, () => void]>)]} /> : null}</div></div><h3 className="mt-3 font-bold">{collection.name}</h3><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{collection.description || collection.collection_type}</p><p className="mt-3 text-xs text-muted-foreground">{memories.filter((item) => item.collection_id === collection.id).length} memories · {collection.created_by_name}</p></div></article>)}{!collections.length ? <div className="sm:col-span-2 xl:col-span-3"><Empty icon={<Archive />} title="Collection নেই" text="Family Admin প্রথম collection তৈরি করলে memory upload করা যাবে।" /></div> : null}</CardContent></Card><Card className="rounded-3xl shadow-none"><CardHeader><CardTitle>Privacy model</CardTitle></CardHeader><CardContent className="space-y-4"><Privacy icon={<Users />} title="Family" text="Approved family members দেখতে পারবেন।" /><Privacy icon={<ShieldCheck />} title="Admins only" text="Owner, Family Admin ও Manager access পাবেন।" /><Privacy icon={<LockKeyhole />} title="Private" text="শুধু uploader document দেখতে পারবেন।" /><Privacy icon={<Timer />} title="Time lock" text="Unlock date-এর আগে capsule message API-তেও প্রকাশ হয় না।" /></CardContent></Card></section>

    <Tabs defaultValue="memories" className="space-y-4"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-2xl bg-muted/70 p-1"><TabsTrigger value="memories">{pick("স্মৃতি", "Memories")}</TabsTrigger><TabsTrigger value="stories">{pick("ঐতিহ্য", "Heritage")}</TabsTrigger><TabsTrigger value="vault">{pick("ভল্ট", "Vault")}</TabsTrigger><TabsTrigger value="assets">{pick("সম্পদ", "Assets")}</TabsTrigger><TabsTrigger value="capsules">{pick("টাইম ক্যাপসুল", "Time capsules")}</TabsTrigger></TabsList>
      <TabsContent value="memories"><Section title="Digital memory gallery" description="Photo, video, audio ও historical documents" action={<Button className="rounded-xl" onClick={() => openUpload("memory")} disabled={!activeCollections.length || migrationRequired}><Upload /> Upload memory</Button>}><div className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{memories.map((memory) => { const file = fileFor("memory", memory.id); return <MemoryCard key={memory.id} memory={memory} file={file} collection={collectionName(memory.collection_id)} canManage={canManage} saving={saving} onArchive={() => void updateStatus("memory", memory.id, memory.status === "active" ? "archived" : "active")} onDelete={file ? () => void deleteFile(file.id) : undefined} />; })}{!memories.length ? <div className="sm:col-span-2 lg:col-span-3 xl:col-span-4"><Empty icon={<Camera />} title="কোনো স্মৃতি upload হয়নি" text="পুরোনো ছবি, ভিডিও, কণ্ঠস্বর বা documents সংরক্ষণ করুন।" /></div> : null}</div></Section></TabsContent>
      <TabsContent value="stories"><Section title="Family history & oral stories" description="বয়োজ্যেষ্ঠদের স্মৃতি, বংশের ইতিহাস এবং গুরুত্বপূর্ণ ঘটনা" action={<Button className="rounded-xl" onClick={() => openCreate("story")} disabled={migrationRequired}><Plus /> Story</Button>}><div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3">{stories.map((story) => <article key={story.id} className="rounded-2xl border p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><Status value={story.status} /><Badge variant="outline">{story.visibility}</Badge></div>{(canManage || story.is_mine) ? <Menu disabled={saving} items={[...(canManage && story.status !== "published" ? [["Publish", () => void updateStatus("story", story.id, "published")], ["Archive", () => void updateStatus("story", story.id, "archived")]] as Array<[string, () => void]> : story.status !== "archived" ? [["Archive", () => void updateStatus("story", story.id, "archived")]] as Array<[string, () => void]> : []), ["Edit details", () => openEdit("story", story)], ["Delete permanently", () => void remove("story", story.id)]]} /> : null}</div><h3 className="mt-4 text-lg font-bold">{story.title}</h3><p className="mt-2 line-clamp-5 whitespace-pre-line text-sm leading-6 text-muted-foreground">{story.content}</p><p className="mt-4 text-xs text-muted-foreground">{story.story_date ? date.format(new Date(story.story_date)) : "Undated"} · {story.storyteller || story.author_name}{story.place ? ` · ${story.place}` : ""}</p></article>)}{!stories.length ? <div className="md:col-span-2 xl:col-span-3"><Empty icon={<ScrollText />} title="Family history লেখা হয়নি" text="বয়োজ্যেষ্ঠদের গল্প ও পারিবারিক ইতিহাস লিখুন।" /></div> : null}</div></Section></TabsContent>
      <TabsContent value="vault"><Section title="Secure document vault" description="Private identity, property, legal ও financial document index" action={<Button className="rounded-xl" onClick={() => openUpload("vault")} disabled={migrationRequired}><Upload /> Document</Button>}><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Document</TableHead><TableHead>Owner</TableHead><TableHead>Masked ID</TableHead><TableHead>Issuer</TableHead><TableHead>Expiry</TableHead><TableHead>Privacy</TableHead><TableHead>File</TableHead></TableRow></TableHeader><TableBody>{documents.map((document) => { const file = fileFor("vault_document", document.id); const expiryState = expiryLabel(document.expiry_date); return <TableRow key={document.id}><TableCell><p className="font-semibold">{document.title}</p><p className="text-xs text-muted-foreground">{document.category.replaceAll("_", " ")}</p></TableCell><TableCell>{document.owner_name || "—"}</TableCell><TableCell>{document.document_number_masked || "Not stored"}</TableCell><TableCell>{document.issuer || "—"}</TableCell><TableCell><span className={expiryState.urgent ? "font-bold text-destructive" : ""}>{expiryState.label}</span></TableCell><TableCell><Badge variant="outline">{document.visibility}</Badge></TableCell><TableCell>{file ? <div className="flex gap-1"><Button asChild size="sm" variant="outline" className="rounded-xl"><a href={`/api/archive-file/${file.id}`} target="_blank" rel="noreferrer"><FileText /> Open</a></Button>{(canManage || document.is_mine) ? <Button size="icon-sm" variant="ghost" aria-label="Delete document" onClick={() => void deleteFile(file.id)} disabled={saving}><Trash2 /></Button> : null}</div> : "—"}</TableCell></TableRow>; })}<EmptyRows show={!documents.length} columns={7} /></TableBody></Table></div></Section></TabsContent>
      <TabsContent value="assets"><Section title="Family asset & property register" description="Land, house, vehicle, business এবং investment records" action={canManage ? <Button className="rounded-xl" onClick={() => openCreate("asset")} disabled={migrationRequired}><Plus /> Asset</Button> : undefined}><div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3">{assets.map((asset) => <article key={asset.id} className="rounded-2xl border p-5"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Building2 className="size-5" /></span><div className="flex gap-2"><Status value={asset.status} /><Badge variant="outline">{asset.visibility}</Badge>{canManage ? <Menu disabled={saving} items={[...(asset.status === "active" ? [["Mark disputed", () => void updateStatus("asset", asset.id, "disputed")], ["Mark sold", () => void updateStatus("asset", asset.id, "sold")]] as Array<[string, () => void]> : [["Activate", () => void updateStatus("asset", asset.id, "active")]] as Array<[string, () => void]>), ["Edit details", () => openEdit("asset", asset)], ["Delete permanently", () => void remove("asset", asset.id)]]} /> : null}</div></div><h3 className="mt-4 text-lg font-bold">{asset.title}</h3><p className="mt-1 text-sm text-muted-foreground">{assetLabels[asset.asset_type]} · {asset.ownership || "Ownership not listed"}</p><p className="mt-4 text-2xl font-black">{money.format(n(asset.estimated_value))}</p><p className="mt-1 text-xs text-muted-foreground">{asset.location || "Location private"}{asset.identifier_masked ? ` · ${asset.identifier_masked}` : ""}</p></article>)}{!assets.length ? <div className="md:col-span-2 xl:col-span-3"><Empty icon={<Landmark />} title="Asset register খালি" text="Family Admin protected property index তৈরি করতে পারবেন।" /></div> : null}</div></Section></TabsContent>
      <TabsContent value="capsules"><Section title="Digital time capsules" description="ভবিষ্যতের জন্য locked letter, memory ও family message" action={<Button className="rounded-xl" onClick={() => openCreate("capsule")} disabled={migrationRequired}><Plus /> Capsule</Button>}><div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3">{capsules.map((capsule) => <article key={capsule.id} className={`rounded-2xl border p-5 ${capsule.is_unlocked ? "bg-emerald-500/5" : "bg-muted/20"}`}><div className="flex items-start justify-between"><span className={`grid size-11 place-items-center rounded-2xl ${capsule.is_unlocked ? "bg-emerald-500/15 text-emerald-700" : "bg-violet-500/10 text-violet-700"}`}>{capsule.is_unlocked ? <PackageOpen className="size-5" /> : <Hourglass className="size-5" />}</span><div className="flex gap-2"><Badge variant={capsule.is_unlocked ? "secondary" : "outline"}>{capsule.is_unlocked ? "Unlocked" : "Locked"}</Badge>{(canManage || capsule.is_mine) && !capsule.is_unlocked ? <Menu disabled={saving} items={[["Cancel capsule", () => void updateStatus("capsule", capsule.id, "cancelled")], ["Edit details", () => openEdit("capsule", capsule)], ["Delete permanently", () => void remove("capsule", capsule.id)]]} /> : null}</div></div><h3 className="mt-4 text-lg font-bold">{capsule.title}</h3><p className="mt-1 text-sm text-muted-foreground">For: {capsule.recipient_names || "Whole family"}</p>{capsule.is_unlocked ? <p className="mt-4 whitespace-pre-line rounded-xl border bg-card p-4 text-sm leading-6">{capsule.message}</p> : <div className="mt-4 rounded-xl border border-dashed p-4 text-center"><LockKeyhole className="mx-auto size-5 text-muted-foreground" /><p className="mt-2 text-xs text-muted-foreground">Unlocks {dateTime.format(new Date(capsule.unlock_at))}</p></div>}</article>)}{!capsules.length ? <div className="md:col-span-2 xl:col-span-3"><Empty icon={<Hourglass />} title="Time capsule নেই" text="ভবিষ্যতের প্রজন্ম বা বিশেষ দিনের জন্য message lock করুন।" /></div> : null}</div></Section></TabsContent>
    </Tabs>

    <Dialog open={Boolean(kind)} onOpenChange={(open) => { if (!open) { setKind(null); setEditingRecord(null); } }}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-2xl"><DialogHeader><DialogTitle>{editingRecord ? pick(`${kind} সম্পাদনা`, `Edit ${kind}`) : kind ? titles[kind] : pick("নতুন রেকর্ড", "New record")}</DialogTitle><DialogDescription>{editingRecord ? pick("সংরক্ষিত তথ্য আপডেট করুন; গোপনীয়তার নিয়ম অপরিবর্তিত থাকবে।", "Update saved metadata; privacy rules remain unchanged.") : pick("আর্কাইভের তথ্য পরিষ্কার ও গোপনীয়তা-সচেতন রাখুন।", "Keep archive metadata clear and privacy-aware.")}</DialogDescription></DialogHeader>{kind ? <CreateForm kind={kind} form={form} setForm={setForm} canManage={canManage} /> : null}<DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => { setKind(null); setEditingRecord(null); }}>{pick("বাতিল", "Cancel")}</Button><Button className="rounded-xl" onClick={() => void create()} disabled={saving}>{saving ? <LoaderCircle className="size-4 animate-spin" /> : editingRecord ? <Pencil className="size-4" /> : <CheckCircle2 className="size-4" />} {editingRecord ? pick("আপডেট", "Update") : pick("সেভ", "Save")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(uploadMode)} onOpenChange={(open) => !open && setUploadMode(null)}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-2xl"><DialogHeader><DialogTitle>{uploadMode === "memory" ? pick("স্মৃতি আপলোড", "Memory upload") : pick("সিকিউর ভল্ট আপলোড", "Secure vault upload")}</DialogTitle><DialogDescription>{uploadMode === "memory" ? pick("ছবি, ভিডিও, অডিও, PDF বা Word; সর্বোচ্চ ৩০ MB।", "Image, video, audio, PDF or Word; maximum 30 MB.") : pick("ছবি, PDF বা Word; সর্বোচ্চ ২০ MB। পূর্ণ নম্বরের পরিবর্তে মাস্ক করা নম্বর ব্যবহার করুন।", "Image, PDF or Word; maximum 20 MB. Use a masked number instead of the full document number.")}</DialogDescription></DialogHeader><UploadForm mode={uploadMode ?? "memory"} form={uploadForm} setForm={setUploadForm} collections={activeCollections} file={uploadFile} setFile={setUploadFile} /><DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => setUploadMode(null)}>{pick("বাতিল", "Cancel")}</Button><Button className="rounded-xl" onClick={() => void upload()} disabled={saving || !uploadFile}>{saving ? <LoaderCircle className="size-4 animate-spin" /> : <Upload className="size-4" />} {pick("আপলোড", "Upload")}</Button></DialogFooter></DialogContent></Dialog>
  </main>;
}

function CreateForm({ kind, form, setForm, canManage }: { kind: Kind; form: Form; setForm: (form: Form) => void; canManage: boolean }) {
  const { pick } = useLocale();
  const set = (key: string, value: string) => setForm({ ...form, [key]: value }); const input = (key: string, label: string, type = "text", props: Record<string, string> = {}) => <Field label={label}><Input type={type} value={form[key] ?? ""} onChange={(event) => set(key, event.target.value)} {...props} /></Field>; const select = (key: string, label: string, options: string[][]) => <Field label={label}><Native value={form[key]} onChange={(value) => set(key, value)} options={options} /></Field>;
  const privacy = [["family", pick("পুরো পরিবার", "Whole family")], ["admins", pick("শুধু অ্যাডমিন", "Admins only")], ["private", pick("শুধু আমি", "Only me")]];
  if (kind === "collection") return <div className="grid gap-4 py-2 sm:grid-cols-2">{input("name", pick("সংগ্রহের নাম", "Collection name"))}{select("collectionType", pick("ধরন", "Type"), [["album", pick("অ্যালবাম", "Album")], ["heritage", pick("ঐতিহ্য", "Heritage")], ["documents", pick("ডকুমেন্ট", "Documents")], ["property", pick("সম্পত্তি", "Property")], ["time_capsule", pick("টাইম ক্যাপসুল", "Time capsule")], ["other", pick("অন্যান্য", "Other")]])}{select("visibility", pick("গোপনীয়তা", "Privacy"), privacy)}{input("coverColor", pick("কভার রং", "Cover color"), "color")}<div className="sm:col-span-2">{input("description", pick("বিবরণ", "Description"))}</div></div>;
  if (kind === "story") return <div className="grid gap-4 py-2 sm:grid-cols-2">{input("title", pick("গল্পের শিরোনাম", "Story title"))}{input("storyDate", pick("ঐতিহাসিক তারিখ", "Historical date"), "date")}{input("storyteller", pick("কথক / উৎস", "Storyteller / source"))}{input("place", pick("স্থান", "Place"))}{input("peopleTags", pick("ব্যক্তির ট্যাগ", "People tags"), "text", { placeholder: pick("দাদা, বড় চাচা, ...", "Grandfather, uncle, ...") })}{select("visibility", pick("দৃশ্যমানতা", "Visibility"), privacy.slice(0, 2))}<div className="sm:col-span-2"><Field label={pick("পূর্ণ গল্প", "Full story")}><Textarea rows={9} value={form.content ?? ""} onChange={(event) => set("content", event.target.value)} /></Field></div></div>;
  if (kind === "asset") return <div className="grid gap-4 py-2 sm:grid-cols-2">{input("title", pick("সম্পদের শিরোনাম", "Asset title"))}{select("assetType", pick("ধরন", "Type"), [["land", pick("জমি", "Land")], ["house", pick("বাড়ি", "House")], ["flat", pick("ফ্ল্যাট", "Flat")], ["vehicle", pick("যানবাহন", "Vehicle")], ["business", pick("ব্যবসা", "Business")], ["investment", pick("বিনিয়োগ", "Investment")], ["jewelry", pick("গহনা", "Jewelry")], ["other", pick("অন্যান্য", "Other")]])}{input("ownership", pick("মালিকানা", "Ownership"))}{input("location", pick("স্থান", "Location"))}{input("identifierMasked", pick("মাস্ক করা পরিচিতি", "Masked identifier"))}{input("acquisitionDate", pick("অর্জনের তারিখ", "Acquisition date"), "date")}{input("estimatedValue", pick("আনুমানিক মূল্য", "Estimated value"), "number", { min: "0" })}{select("visibility", pick("দৃশ্যমানতা", "Visibility"), privacy.slice(0, 2).reverse())}<div className="sm:col-span-2"><Field label={pick("নোট", "Notes")}><Textarea rows={4} value={form.notes ?? ""} onChange={(event) => set("notes", event.target.value)} /></Field></div></div>;
  return <div className="grid gap-4 py-2 sm:grid-cols-2">{input("title", pick("ক্যাপসুলের শিরোনাম", "Capsule title"))}{input("recipientNames", pick("প্রাপক", "Recipients"))}{input("unlockAt", pick("খোলার সময়", "Unlock time"), "datetime-local")}{select("visibility", pick("দৃশ্যমানতা", "Visibility"), privacy.slice(0, 2))}<div className="sm:col-span-2"><Field label={pick("লক করা বার্তা", "Locked message")}><Textarea rows={8} value={form.message ?? ""} onChange={(event) => set("message", event.target.value)} /></Field></div>{!canManage ? <p className="sm:col-span-2 text-xs text-muted-foreground">{pick("ক্যাপসুল খোলার আগে শুধু আপনি এটি বাতিল করতে পারবেন।", "Only you can cancel the capsule before it unlocks.")}</p> : null}</div>;
}

function UploadForm({ mode, form, setForm, collections, file, setFile }: { mode: "memory" | "vault"; form: Form; setForm: (form: Form) => void; collections: ArchiveCollection[]; file: File | null; setFile: (file: File | null) => void }) {
  const { pick } = useLocale();
  const set = (key: string, value: string) => setForm({ ...form, [key]: value });
  const input = (key: string, label: string, type = "text") => <Field label={label}><Input type={type} value={form[key] ?? ""} onChange={(event) => set(key, event.target.value)} /></Field>;
  const privacy = [["family", pick("পুরো পরিবার", "Whole family")], ["admins", pick("শুধু অ্যাডমিন", "Admins only")], ["private", pick("শুধু আমি", "Only me")]];
  if (mode === "memory") return <div className="grid gap-4 py-2 sm:grid-cols-2"><Field label={pick("সংগ্রহ", "Collection")}><Native value={form.collectionId} onChange={(value) => set("collectionId", value)} options={collections.map((item) => [item.id, item.name])} placeholder={pick("সংগ্রহ নির্বাচন করুন", "Select a collection")} /></Field>{input("title", pick("শিরোনাম", "Title"))}{input("memoryDate", pick("স্মৃতির তারিখ", "Memory date"), "date")}{input("place", pick("স্থান", "Place"))}{input("peopleTags", pick("ব্যক্তির ট্যাগ", "People tags"))}<Field label={pick("গোপনীয়তা", "Privacy")}><Native value={form.visibility} onChange={(value) => set("visibility", value)} options={privacy} /></Field><div className="sm:col-span-2">{input("description", pick("বিবরণ", "Description"))}</div><div className="sm:col-span-2"><FilePicker mode={mode} file={file} setFile={setFile} /></div></div>;
  return <div className="grid gap-4 py-2 sm:grid-cols-2">{input("title", pick("ডকুমেন্টের শিরোনাম", "Document title"))}<Field label={pick("শ্রেণি", "Category")}><Native value={form.category} onChange={(value) => set("category", value)} options={[["property_deed", pick("সম্পত্তির দলিল", "Property deed")], ["nid", "NID"], ["passport", pick("পাসপোর্ট", "Passport")], ["birth_certificate", pick("জন্মনিবন্ধন", "Birth certificate")], ["legal", pick("আইনি", "Legal")], ["financial", pick("আর্থিক", "Financial")], ["insurance", pick("বীমা", "Insurance")], ["education", pick("শিক্ষা", "Education")], ["other", pick("অন্যান্য", "Other")]]} /></Field>{input("ownerName", pick("ডকুমেন্টের মালিক", "Document owner"))}{input("documentNumberMasked", pick("মাস্ক নম্বর (উদাহরণ ****1234)", "Masked number (example ****1234)"))}{input("issuer", pick("ইস্যুকারী", "Issuer"))}{input("issueDate", pick("ইস্যুর তারিখ", "Issue date"), "date")}{input("expiryDate", pick("মেয়াদ শেষের তারিখ", "Expiry date"), "date")}<Field label={pick("গোপনীয়তা", "Privacy")}><Native value={form.visibility} onChange={(value) => set("visibility", value)} options={privacy} /></Field><div className="sm:col-span-2"><Field label={pick("নোট", "Notes")}><Textarea rows={3} value={form.notes ?? ""} onChange={(event) => set("notes", event.target.value)} /></Field></div><div className="sm:col-span-2"><FilePicker mode={mode} file={file} setFile={setFile} /></div></div>;
}
function FilePicker({ mode, file, setFile }: { mode: "memory" | "vault"; file: File | null; setFile: (file: File | null) => void }) { const { pick } = useLocale(); return <Field label={pick("ফাইল", "File")}><Input type="file" accept={mode === "memory" ? "image/*,video/mp4,video/webm,audio/*,application/pdf,.doc,.docx" : "image/jpeg,image/png,image/webp,application/pdf,.doc,.docx"} onChange={(event) => setFile(event.target.files?.[0] ?? null)} />{file ? <p className="text-xs text-muted-foreground">{file.name} · {fileSize(file.size)}</p> : null}</Field>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
function Native({ value, onChange, options, placeholder }: { value?: string; onChange: (value: string) => void; options: string[][]; placeholder?: string }) { return <select value={value ?? ""} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15">{placeholder ? <option value="">{placeholder}</option> : null}{options.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select>; }
function fileSize(size: number) { return size < 1024 * 1024 ? `${(size / 1024).toFixed(1)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`; }
function expiryLabel(value: string | null) { if (!value) return { label: "No expiry", urgent: false }; const days = Math.ceil((new Date(value).getTime() - Date.now()) / 86400000); if (days < 0) return { label: `Expired ${date.format(new Date(value))}`, urgent: true }; if (days <= 90) return { label: `${days} days · ${date.format(new Date(value))}`, urgent: true }; return { label: date.format(new Date(value)), urgent: false }; }
function Metric({ icon, label, value, note, tone }: { icon: ReactNode; label: string; value: string; note: string; tone: "violet" | "cyan" | "amber" | "emerald" }) { const colors = { violet: "bg-violet-500/10 text-violet-700 dark:text-violet-300", cyan: "bg-cyan-500/10 text-cyan-700 dark:text-cyan-300", amber: "bg-amber-500/10 text-amber-700 dark:text-amber-300", emerald: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" }; return <Card className="rounded-2xl shadow-none"><CardContent className="flex items-start gap-4 p-5"><span className={`grid size-11 shrink-0 place-items-center rounded-2xl ${colors[tone]}`}>{icon}</span><div className="min-w-0"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 truncate text-2xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div></CardContent></Card>; }
function Privacy({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary">{icon}</span><div><p className="font-semibold">{title}</p><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{text}</p></div></div>; }
function Section({ title, description, action, children }: { title: string; description: string; action?: ReactNode; children: ReactNode }) { const { locale } = useLocale(); const titlesBn: Record<string, string> = { "Digital memory gallery": "ডিজিটাল স্মৃতি গ্যালারি", "Family history & oral stories": "পারিবারিক ইতিহাস ও মুখে বলা গল্প", "Secure document vault": "সিকিউর ডকুমেন্ট ভল্ট", "Family asset & property register": "পারিবারিক সম্পদ ও সম্পত্তি রেজিস্টার", "Digital time capsules": "ডিজিটাল টাইম ক্যাপসুল" }; const descriptionsBn: Record<string, string> = { "Photo, video, audio ও historical documents": "ছবি, ভিডিও, অডিও ও ঐতিহাসিক ডকুমেন্ট", "Private identity, property, legal ও financial document index": "ব্যক্তিগত পরিচয়, সম্পত্তি, আইনি ও আর্থিক ডকুমেন্ট সূচি", "Land, house, vehicle, business এবং investment records": "জমি, বাড়ি, যানবাহন, ব্যবসা ও বিনিয়োগের রেকর্ড", "ভবিষ্যতের জন্য locked letter, memory ও family message": "ভবিষ্যতের জন্য লক করা চিঠি, স্মৃতি ও পারিবারিক বার্তা" }; return <Card className="overflow-hidden rounded-3xl py-0 shadow-none"><CardHeader className="flex-row items-start justify-between gap-4 border-b p-5 md:p-6"><div><CardTitle>{locale === "bn" ? titlesBn[title] ?? title : title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{locale === "bn" ? descriptionsBn[description] ?? description : description}</p></div>{action}</CardHeader><CardContent className="p-0">{children}</CardContent></Card>; }
function Status({ value }: { value: string }) { const { locale } = useLocale(); const good = ["active", "published", "opened"]; const bad = ["archived", "cancelled", "sold", "inactive", "disputed"]; const bn: Record<string, string> = { active: "সক্রিয়", published: "প্রকাশিত", opened: "খোলা", archived: "আর্কাইভ", cancelled: "বাতিল", sold: "বিক্রি", inactive: "নিষ্ক্রিয়", disputed: "বিতর্কিত", pending: "অপেক্ষমাণ" }; return <Badge variant={bad.includes(value) ? "destructive" : good.includes(value) ? "secondary" : "outline"} className="capitalize">{locale === "bn" ? bn[value] ?? value : value.replaceAll("_", " ")}</Badge>; }
function Menu({ items, disabled }: { items: Array<[string, () => void]>; disabled: boolean }) { const { locale } = useLocale(); const bn: Record<string, string> = { Archive: "আর্কাইভ", Activate: "সক্রিয় করুন", "Edit details": "বিস্তারিত সম্পাদনা", "Delete permanently": "স্থায়ীভাবে মুছুন", Publish: "প্রকাশ করুন", "Mark disputed": "বিতর্কিত চিহ্নিত করুন", "Mark sold": "বিক্রি চিহ্নিত করুন", "Cancel capsule": "ক্যাপসুল বাতিল" }; if (!items.length) return null; return <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon-sm" variant="ghost" disabled={disabled}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{items.map(([label, run]) => <DropdownMenuItem key={label} onClick={run}>{locale === "bn" ? bn[label] ?? label : label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>; }
function MemoryCard({ memory, file, collection, canManage, saving, onArchive, onDelete }: { memory: ArchiveMemory; file?: ArchiveFile; collection: string; canManage: boolean; saving: boolean; onArchive: () => void; onDelete?: () => void }) { const image = file?.mime_type.startsWith("image/"); return <article className="overflow-hidden rounded-2xl border bg-card">{image && file ? <img src={`/api/archive-file/${file.id}`} alt={memory.title} className="aspect-[4/3] w-full object-cover" /> : <div className="grid aspect-[4/3] place-items-center bg-[linear-gradient(135deg,hsl(var(--muted)),hsl(var(--primary)/.12))]"><FileArchive className="size-12 text-muted-foreground/50" /></div>}<div className="p-4"><div className="flex items-start justify-between gap-2"><div className="flex gap-2"><Badge variant="secondary">{memory.memory_type}</Badge><Badge variant="outline">{memory.visibility}</Badge></div>{(canManage || memory.is_mine) ? <Menu disabled={saving} items={[[memory.status === "active" ? "Archive" : "Activate", onArchive], ...(onDelete ? [["Delete permanently", onDelete]] as Array<[string, () => void]> : [])]} /> : null}</div><h3 className="mt-3 font-bold">{memory.title}</h3><p className="mt-1 text-xs text-muted-foreground">{collection}{memory.memory_date ? ` · ${date.format(new Date(memory.memory_date))}` : ""}</p><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{memory.description || memory.place || `Uploaded by ${memory.uploaded_by_name}`}</p>{file ? <Button asChild size="sm" variant="outline" className="mt-4 rounded-xl"><a href={`/api/archive-file/${file.id}`} target="_blank" rel="noreferrer">Open file</a></Button> : null}</div></article>; }
function EmptyRows({ show, columns }: { show: boolean; columns: number }) { return show ? <TableRow><TableCell colSpan={columns} className="h-32 text-center text-muted-foreground">এখনও কোনো document নেই।</TableCell></TableRow> : null; }
function Empty({ icon, title, text, action }: { icon: ReactNode; title: string; text: string; action?: ReactNode }) { const { locale } = useLocale(); const titlesBn: Record<string, string> = { "Collection নেই": "কোনো সংগ্রহ নেই", "কোনো স্মৃতি upload হয়নি": "কোনো স্মৃতি আপলোড হয়নি", "Family history লেখা হয়নি": "পারিবারিক ইতিহাস লেখা হয়নি", "Asset register খালি": "সম্পদ রেজিস্টার খালি", "Time capsule নেই": "কোনো টাইম ক্যাপসুল নেই", "Family access সক্রিয় নয়": "পারিবারিক অ্যাক্সেস সক্রিয় নয়" }; const textBn: Record<string, string> = { "Family Admin প্রথম collection তৈরি করলে memory upload করা যাবে।": "Family Admin প্রথম সংগ্রহ তৈরি করলে স্মৃতি আপলোড করা যাবে।", "পুরোনো ছবি, ভিডিও, কণ্ঠস্বর বা documents সংরক্ষণ করুন।": "পুরোনো ছবি, ভিডিও, কণ্ঠস্বর বা ডকুমেন্ট সংরক্ষণ করুন।", "বয়োজ্যেষ্ঠদের গল্প ও পারিবারিক ইতিহাস লিখুন।": "বয়োজ্যেষ্ঠদের গল্প ও পারিবারিক ইতিহাস লিখুন।", "Family Admin protected property index তৈরি করতে পারবেন।": "Family Admin সুরক্ষিত সম্পত্তির সূচি তৈরি করতে পারবেন।", "ভবিষ্যতের প্রজন্ম বা বিশেষ দিনের জন্য message lock করুন।": "ভবিষ্যতের প্রজন্ম বা বিশেষ দিনের জন্য বার্তা লক করুন।" }; return <div className="flex min-h-52 flex-col items-center justify-center p-6 text-center"><span className="text-muted-foreground/50">{icon}</span><h3 className="mt-3 font-bold">{locale === "bn" ? titlesBn[title] ?? title : title}</h3><p className="mt-1 max-w-md text-sm text-muted-foreground">{locale === "bn" ? textBn[text] ?? text : text}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
