"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { CheckCircle2, Clock3, Download, LifeBuoy, LoaderCircle, MessageSquareText, Plus, Search, ShieldCheck } from "lucide-react";
import { useActionFeedback } from "@/components/action-modal-provider";
import { useLocale, type AppLocale } from "@/components/locale-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { ContactPayload, ContactTicket, ContactTicketPriority, ContactTicketStatus } from "@/lib/contact-types";

type Form = { category: string; subject: string; message: string; preferredContact: string; priority: ContactTicketPriority };
const emptyForm: Form = { category: "general", subject: "", message: "", preferredContact: "", priority: "normal" };
const categoryBn: Record<string, string> = { general: "সাধারণ", family_admin: "ফ্যামিলি অ্যাডমিন", technical: "কারিগরি সহায়তা", privacy: "গোপনীয়তা", event: "ইভেন্ট", qurbani: "কোরবানি", finance: "অর্থব্যবস্থা", health: "স্বাস্থ্য", other: "অন্যান্য" };
const statusBn: Record<ContactTicketStatus, string> = { open: "খোলা", in_progress: "কাজ চলছে", waiting_member: "সদস্যের উত্তরের অপেক্ষায়", resolved: "সমাধান হয়েছে", closed: "বন্ধ" };
const priorityBn: Record<ContactTicketPriority, string> = { normal: "সাধারণ", high: "উচ্চ", urgent: "জরুরি" };
const valueLabel = (value: string, locale: AppLocale) => locale === "bn" ? categoryBn[value] ?? statusBn[value as ContactTicketStatus] ?? priorityBn[value as ContactTicketPriority] ?? value : value.replaceAll("_", " ");

export function ContactCenter() {
  const { locale, pick } = useLocale();
  const [, setFeedback] = useActionFeedback();
  const [payload, setPayload] = useState<ContactPayload>({});
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [exporting, setExporting] = useState(false);
  const [query, setQuery] = useState(""), [statusFilter, setStatusFilter] = useState("all");
  const [createOpen, setCreateOpen] = useState(false), [form, setForm] = useState<Form>(emptyForm);
  const [selected, setSelected] = useState<ContactTicket | null>(null);
  const [manage, setManage] = useState({ status: "in_progress" as ContactTicketStatus, priority: "normal" as ContactTicketPriority, adminResponse: "", assignedToName: "" });
  const date = useMemo(() => new Intl.DateTimeFormat(locale === "bn" ? "bn-BD" : "en-BD", { dateStyle: "medium", timeStyle: "short" }), [locale]);
  const tickets = useMemo(() => payload.tickets ?? [], [payload.tickets]), canManage = Boolean(payload.permissions?.canManage);

  const load = useCallback(async () => {
    try { const response = await fetch("/api/contact", { cache: "no-store" }); const data = await response.json() as ContactPayload; if (data.code === "FAMILY_SETUP_REQUIRED") { setPayload(data); return; } if (!response.ok) throw new Error(data.error ?? pick("যোগাযোগ কেন্দ্র লোড হয়নি।", "Could not load Contact & Support.")); setPayload(data); }
    catch (error) { setFeedback(error instanceof Error ? error.message : pick("যোগাযোগ কেন্দ্র লোড হয়নি।", "Could not load Contact & Support.")); }
    finally { setLoading(false); }
  }, [pick, setFeedback]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);

  const visible = useMemo(() => tickets.filter((ticket) => {
    const needle = query.trim().toLowerCase();
    return (statusFilter === "all" || ticket.status === statusFilter) && (!needle || `${ticket.subject} ${ticket.message} ${ticket.created_by_name} ${ticket.admin_response ?? ""}`.toLowerCase().includes(needle));
  }), [query, statusFilter, tickets]);
  const openCount = tickets.filter((item) => ["open", "in_progress", "waiting_member"].includes(item.status)).length;
  const urgentCount = tickets.filter((item) => item.priority === "urgent" && !["resolved", "closed"].includes(item.status)).length;

  async function submit() {
    if (!form.subject.trim() || !form.message.trim()) { setFeedback(pick("বিষয় ও বার্তা লিখুন।", "Enter a subject and message.")); return; }
    setSaving(true); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? pick("অনুরোধ পাঠানো যায়নি।", "Could not submit the request.")); setCreateOpen(false); setForm(emptyForm); await load(); setFeedback(pick("সহায়তার অনুরোধ পাঠানো হয়েছে।", "The support request was submitted.")); } catch (error) { setFeedback(error instanceof Error ? error.message : pick("অনুরোধ পাঠানো যায়নি।", "Could not submit the request.")); } finally { setSaving(false); }
  }
  function openManage(ticket: ContactTicket) { setSelected(ticket); setManage({ status: ticket.status, priority: ticket.priority, adminResponse: ticket.admin_response ?? "", assignedToName: ticket.assigned_to_name ?? "" }); }
  async function update(ticket: ContactTicket, values: Record<string, unknown>) {
    setSaving(true); try { const response = await fetch("/api/contact", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: ticket.id, ...values }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? pick("অনুরোধ হালনাগাদ হয়নি।", "Could not update the request.")); setSelected(null); await load(); setFeedback(pick("সহায়তার অনুরোধ হালনাগাদ হয়েছে।", "The support request was updated.")); } catch (error) { setFeedback(error instanceof Error ? error.message : pick("অনুরোধ হালনাগাদ হয়নি।", "Could not update the request.")); } finally { setSaving(false); }
  }
  async function exportXlsx() {
    setExporting(true); try { const XLSX = await import("xlsx"); const rows = visible.map((item) => ({ [pick("বিষয়", "Subject")]: item.subject, [pick("বিভাগ", "Category")]: valueLabel(item.category, locale), [pick("বার্তা", "Message")]: item.message, [pick("আবেদনকারী", "Requester")]: item.created_by_name, [pick("যোগাযোগ", "Preferred contact")]: item.preferred_contact ?? "", [pick("অগ্রাধিকার", "Priority")]: valueLabel(item.priority, locale), [pick("অবস্থা", "Status")]: valueLabel(item.status, locale), [pick("অ্যাডমিন উত্তর", "Admin response")]: item.admin_response ?? "", [pick("দায়িত্বপ্রাপ্ত", "Assigned to")]: item.assigned_to_name ?? "", [pick("তৈরির সময়", "Created at")]: item.created_at, [pick("সমাধানের সময়", "Resolved at")]: item.resolved_at ?? "" })); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), pick("সহায়তা অনুরোধ", "Support Requests")); XLSX.writeFile(book, `${payload.family?.name_en?.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "family"}-contact-support.xlsx`); setFeedback(pick("যোগাযোগ ও সহায়তা XLSX তৈরি হয়েছে।", "The Contact & Support XLSX was created.")); } catch { setFeedback(pick("XLSX তৈরি হয়নি।", "The XLSX could not be created.")); } finally { setExporting(false); }
  }

  if (loading) return <main className="grid min-h-[calc(100vh-4rem)] place-items-center"><LoaderCircle className="size-7 animate-spin text-primary" /></main>;
  if (payload.code === "FAMILY_SETUP_REQUIRED") return <main className="grid min-h-[calc(100vh-4rem)] place-items-center p-6 text-center"><div><LifeBuoy className="mx-auto size-10 text-muted-foreground" /><h1 className="mt-4 text-xl font-bold">{pick("ফ্যামিলি অ্যাক্সেস প্রয়োজন", "Family access required")}</h1><Button asChild className="mt-4"><a href="/setup">{pick("ফ্যামিলিতে যোগ দিন", "Join a family")}</a></Button></div></main>;
  return <main className="mx-auto w-full max-w-[1450px] space-y-5 px-4 py-5 md:px-7 md:py-7">
    <section className="overflow-hidden rounded-3xl bg-[linear-gradient(125deg,#0f3d56_0%,#0f766e_55%,#7c3f14_100%)] p-5 text-white shadow-xl md:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><p className="flex items-center gap-2 text-sm text-cyan-100"><LifeBuoy className="size-4" /> {pick("পরিবারের সহায়তা কেন্দ্র", "Family help desk")}</p><h1 className="mt-2 text-2xl font-bold md:text-4xl">{pick("যোগাযোগ ও সহায়তা", "Contact & Support")}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/75">{pick("ফ্যামিলি অ্যাডমিনকে প্রশ্ন, গোপনীয়তা বা কারিগরি সমস্যা পাঠান এবং সমাধানের অগ্রগতি দেখুন।", "Send family-admin, privacy, or technical questions and track their resolution.")}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => void exportXlsx()} disabled={exporting || !visible.length}>{exporting ? <LoaderCircle className="size-4 animate-spin" /> : <Download className="size-4" />} XLSX</Button><Button className="bg-cyan-400 text-slate-950 hover:bg-cyan-300" onClick={() => setCreateOpen(true)} disabled={payload.migrationRequired}><Plus /> {pick("নতুন অনুরোধ", "New request")}</Button></div></div></section>
    {payload.migrationRequired ? <div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-800 dark:bg-amber-950/35 dark:text-amber-100">{pick("যোগাযোগ কেন্দ্র চালু করতে Supabase SQL Editor-এ", "To activate Contact & Support, run")} <b>supabase/migrations/20260930_family_contact_support.sql</b> {pick("চালান।", "in the Supabase SQL Editor.")}</div> : null}
    <section className="grid gap-4 sm:grid-cols-3"><Metric icon={<MessageSquareText />} label={pick("মোট অনুরোধ", "Total requests")} value={tickets.length} /><Metric icon={<Clock3 />} label={pick("খোলা অনুরোধ", "Open requests")} value={openCount} /><Metric icon={<ShieldCheck />} label={pick("জরুরি", "Urgent")} value={urgentCount} /></section>
    <Card className="rounded-3xl shadow-none"><CardContent className="space-y-4 p-5"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={pick("বিষয়, বার্তা বা সদস্য খুঁজুন", "Search subject, message, or member")} className="pl-9" /></div><Native value={statusFilter} onChange={setStatusFilter} options={[["all", pick("সব অবস্থা", "All statuses")], ...(["open", "in_progress", "waiting_member", "resolved", "closed"] as ContactTicketStatus[]).map((value) => [value, valueLabel(value, locale)])]} /></div><div className="grid gap-3 lg:grid-cols-2">{visible.map((ticket) => <article key={ticket.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><Badge variant={ticket.priority === "urgent" ? "destructive" : "outline"}>{valueLabel(ticket.priority, locale)}</Badge><Badge variant={["resolved", "closed"].includes(ticket.status) ? "secondary" : "outline"}>{valueLabel(ticket.status, locale)}</Badge><Badge variant="outline">{valueLabel(ticket.category, locale)}</Badge></div><Button size="sm" variant="outline" onClick={() => openManage(ticket)}>{canManage ? pick("পরিচালনা", "Manage") : pick("বিস্তারিত", "Details")}</Button></div><h2 className="mt-3 font-bold">{ticket.subject}</h2><p className="mt-2 line-clamp-3 text-sm text-muted-foreground">{ticket.message}</p><p className="mt-3 text-xs text-muted-foreground">{ticket.created_by_name} · {date.format(new Date(ticket.created_at))}</p>{ticket.admin_response ? <div className="mt-3 rounded-xl bg-primary/8 p-3 text-sm"><b>{pick("অ্যাডমিন উত্তর:", "Admin response:")}</b> {ticket.admin_response}</div> : null}</article>)}{!visible.length ? <p className="col-span-full py-14 text-center text-sm text-muted-foreground">{pick("কোনো সহায়তার অনুরোধ পাওয়া যায়নি।", "No support requests were found.")}</p> : null}</div></CardContent></Card>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="rounded-3xl sm:max-w-xl"><DialogHeader><DialogTitle>{pick("সহায়তার অনুরোধ পাঠান", "Send a support request")}</DialogTitle><DialogDescription>{pick("পরিবারের অ্যাডমিনরা অনুরোধটি দেখতে এবং উত্তর দিতে পারবেন।", "Family admins can review and respond to this request.")}</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label={pick("বিভাগ", "Category")}><Native value={form.category} onChange={(value) => setForm({ ...form, category: value })} options={Object.keys(categoryBn).map((value) => [value, valueLabel(value, locale)])} /></Field><Field label={pick("অগ্রাধিকার", "Priority")}><Native value={form.priority} onChange={(value) => setForm({ ...form, priority: value as ContactTicketPriority })} options={(["normal", "high", "urgent"] as ContactTicketPriority[]).map((value) => [value, valueLabel(value, locale)])} /></Field><div className="sm:col-span-2"><Field label={pick("বিষয়", "Subject")}><Input value={form.subject} maxLength={180} onChange={(event) => setForm({ ...form, subject: event.target.value })} /></Field></div><div className="sm:col-span-2"><Field label={pick("বার্তা", "Message")}><Textarea rows={7} value={form.message} maxLength={5000} onChange={(event) => setForm({ ...form, message: event.target.value })} /></Field></div><div className="sm:col-span-2"><Field label={pick("পছন্দের যোগাযোগ", "Preferred contact")}><Input value={form.preferredContact} onChange={(event) => setForm({ ...form, preferredContact: event.target.value })} placeholder={pick("ফোন, ইমেইল বা WhatsApp (ঐচ্ছিক)", "Phone, email, or WhatsApp (optional)")} /></Field></div></div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>{pick("বাতিল", "Cancel")}</Button><Button onClick={() => void submit()} disabled={saving}>{saving ? <LoaderCircle className="size-4 animate-spin" /> : <Plus />} {pick("পাঠান", "Submit")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-2xl">{selected ? <><DialogHeader><DialogTitle>{selected.subject}</DialogTitle><DialogDescription>{selected.created_by_name} · {date.format(new Date(selected.created_at))}</DialogDescription></DialogHeader><div className="space-y-4"><p className="whitespace-pre-wrap rounded-2xl bg-muted/45 p-4 text-sm leading-6">{selected.message}</p>{selected.preferred_contact ? <p className="text-sm"><b>{pick("যোগাযোগ:", "Contact:")}</b> {selected.preferred_contact}</p> : null}{canManage ? <div className="grid gap-4 sm:grid-cols-2"><Field label={pick("অবস্থা", "Status")}><Native value={manage.status} onChange={(value) => setManage({ ...manage, status: value as ContactTicketStatus })} options={(["open", "in_progress", "waiting_member", "resolved", "closed"] as ContactTicketStatus[]).map((value) => [value, valueLabel(value, locale)])} /></Field><Field label={pick("অগ্রাধিকার", "Priority")}><Native value={manage.priority} onChange={(value) => setManage({ ...manage, priority: value as ContactTicketPriority })} options={(["normal", "high", "urgent"] as ContactTicketPriority[]).map((value) => [value, valueLabel(value, locale)])} /></Field><Field label={pick("দায়িত্বপ্রাপ্ত", "Assigned to")}><Input value={manage.assignedToName} onChange={(event) => setManage({ ...manage, assignedToName: event.target.value })} /></Field><div className="sm:col-span-2"><Field label={pick("অ্যাডমিন উত্তর", "Admin response")}><Textarea rows={6} value={manage.adminResponse} onChange={(event) => setManage({ ...manage, adminResponse: event.target.value })} /></Field></div></div> : selected.admin_response ? <p className="rounded-2xl bg-primary/8 p-4 text-sm">{selected.admin_response}</p> : <p className="text-sm text-muted-foreground">{pick("এখনও কোনো উত্তর দেওয়া হয়নি।", "No response has been provided yet.")}</p>}</div><DialogFooter><Button variant="outline" onClick={() => setSelected(null)}>{pick("বন্ধ করুন", "Close")}</Button>{canManage ? <Button onClick={() => void update(selected, manage)} disabled={saving}><CheckCircle2 /> {pick("হালনাগাদ", "Update")}</Button> : !["closed", "resolved"].includes(selected.status) ? <Button onClick={() => void update(selected, { status: "closed" })} disabled={saving}>{pick("অনুরোধ বন্ধ করুন", "Close request")}</Button> : null}</DialogFooter></> : null}</DialogContent></Dialog>
  </main>;
}

function Metric({ icon, label, value }: { icon: ReactNode; label: string; value: number }) { return <Card className="rounded-2xl shadow-none"><CardContent className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary">{icon}</span><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-black">{value}</p></div></CardContent></Card>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
function Native({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[][] }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{options.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select>; }
