"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { BadgeCheck, CalendarClock, CheckCircle2, CircleDollarSign, ClipboardCheck, Download, FileText, Home, HousePlus, ListChecks, LoaderCircle, MoreHorizontal, Phone, Plus, ReceiptText, Settings2, ShieldCheck, ShoppingBasket, Star, Upload, Users, Wrench, X, Zap } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import type { Household, HouseholdDocument, HouseholdPayload, HouseholdTask, MaintenanceRequest, ServiceContact, ShoppingItem, ShoppingList, UtilityBill } from "@/lib/household-types";

type Kind = "household" | "list" | "item" | "bill" | "task" | "contact" | "maintenance";
type Form = Record<string, string>;
const money = new Intl.NumberFormat("bn-BD", { style: "currency", currency: "BDT", maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat("bn-BD", { dateStyle: "medium" });
const dateTime = new Intl.DateTimeFormat("bn-BD", { dateStyle: "medium", timeStyle: "short" });
const today = () => new Date().toISOString().slice(0, 10);
const nowLocal = () => { const value = new Date(); value.setMinutes(value.getMinutes() - value.getTimezoneOffset()); return value.toISOString().slice(0, 16); };
const n = (value: number | string | null | undefined) => Number(value ?? 0) || 0;
const titles: Record<Kind, string> = { household: "নতুন বাসা / Household", list: "নতুন shopping list", item: "বাজারের item", bill: "Utility bill", task: "Shared task", contact: "Service contact", maintenance: "Maintenance request" };

function initial(kind: Kind, householdId = "", listId = ""): Form {
  if (kind === "household") return {};
  if (kind === "list") return { householdId, budgetAmount: "0", neededBy: today() };
  if (kind === "item") return { listId, category: "grocery", quantity: "1", unit: "pcs", estimatedCost: "0", priority: "normal" };
  if (kind === "bill") return { householdId, category: "electricity", billingMonth: today(), dueDate: today(), recurrence: "monthly", amount: "" };
  if (kind === "task") return { householdId, category: "cleaning", dueAt: nowLocal(), recurrence: "none", priority: "normal" };
  if (kind === "contact") return { householdId, serviceType: "electrician", rating: "0", isTrusted: "false" };
  return { householdId, category: "electrical", urgency: "normal", estimatedCost: "0", scheduledAt: "" };
}

export function HouseholdCenter() {
  const [family, setFamily] = useState<HouseholdPayload["family"]>();
  const [households, setHouseholds] = useState<Household[]>([]);
  const [lists, setLists] = useState<ShoppingList[]>([]);
  const [items, setItems] = useState<ShoppingItem[]>([]);
  const [bills, setBills] = useState<UtilityBill[]>([]);
  const [tasks, setTasks] = useState<HouseholdTask[]>([]);
  const [contacts, setContacts] = useState<ServiceContact[]>([]);
  const [maintenance, setMaintenance] = useState<MaintenanceRequest[]>([]);
  const [documents, setDocuments] = useState<HouseholdDocument[]>([]);
  const [canManage, setCanManage] = useState(false);
  const [selectedHousehold, setSelectedHousehold] = useState("all");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [migrationRequired, setMigrationRequired] = useState(false);
  const [setupRequired, setSetupRequired] = useState(false);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [kind, setKind] = useState<Kind | null>(null);
  const [form, setForm] = useState<Form>({});
  const [uploadOpen, setUploadOpen] = useState(false);
  const [uploadForm, setUploadForm] = useState<Form>({ documentType: "receipt" });
  const [uploadFile, setUploadFile] = useState<File | null>(null);

  const load = useCallback(async () => {
    try {
      const response = await fetch("/api/household", { cache: "no-store" }); const payload = await response.json() as HouseholdPayload;
      if (payload.code === "FAMILY_SETUP_REQUIRED") { setSetupRequired(true); return; }
      if (!response.ok) throw new Error(payload.error ?? "Household workspace load হয়নি।");
      setFamily(payload.family); setHouseholds(payload.households ?? []); setLists(payload.shoppingLists ?? []); setItems(payload.shoppingItems ?? []); setBills(payload.bills ?? []); setTasks(payload.tasks ?? []); setContacts(payload.contacts ?? []); setMaintenance(payload.maintenance ?? []); setDocuments(payload.documents ?? []); setCanManage(Boolean(payload.permissions?.canManage)); setMigrationRequired(Boolean(payload.migrationRequired)); setSetupRequired(false);
    } catch (error) { setFeedback(error instanceof Error ? error.message : "Household workspace load হয়নি।"); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const visibleHouseholds = households.filter((item) => item.status === "active");
  const listIds = useMemo(() => new Set(lists.filter((item) => selectedHousehold === "all" || item.household_id === selectedHousehold).map((item) => item.id)), [lists, selectedHousehold]);
  const filteredLists = lists.filter((item) => selectedHousehold === "all" || item.household_id === selectedHousehold);
  const filteredItems = items.filter((item) => listIds.has(item.list_id));
  const filteredBills = bills.filter((item) => selectedHousehold === "all" || item.household_id === selectedHousehold);
  const filteredTasks = tasks.filter((item) => selectedHousehold === "all" || item.household_id === selectedHousehold);
  const filteredMaintenance = maintenance.filter((item) => selectedHousehold === "all" || item.household_id === selectedHousehold);
  const openItems = filteredItems.filter((item) => item.status === "needed");
  const openTasks = filteredTasks.filter((item) => ["todo", "in_progress"].includes(item.status));
  const dueBills = filteredBills.filter((item) => effectiveBillStatus(item) !== "paid" && effectiveBillStatus(item) !== "skipped");
  const dueAmount = dueBills.reduce((sum, item) => sum + n(item.amount), 0);
  const openMaintenance = filteredMaintenance.filter((item) => !["completed", "cancelled"].includes(item.status));

  function householdName(id: string) { return households.find((item) => item.id === id)?.name ?? "Household"; }
  function listName(id: string) { return lists.find((item) => item.id === id)?.title ?? "Shopping list"; }
  function openCreate(next: Kind, seed: Form = {}) { const householdId = selectedHousehold !== "all" ? selectedHousehold : visibleHouseholds[0]?.id ?? ""; setKind(next); setForm({ ...initial(next, householdId, filteredLists.find((item) => item.status === "active")?.id ?? ""), ...seed }); }
  async function action(actionName: string, data: Record<string, unknown>) { const response = await fetch("/api/household/records", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, data }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Record save হয়নি।"); }
  async function create() { if (!kind) return; setSaving(true); try { await action(`create_${kind}`, form); setKind(null); await load(); setFeedback(`${titles[kind]} save হয়েছে।`); } catch (error) { setFeedback(error instanceof Error ? error.message : "Record save হয়নি।"); } finally { setSaving(false); } }
  async function status(entity: string, id: string, value: string, extra: Record<string, unknown> = {}) { setSaving(true); try { await action("update_status", { entity, id, status: value, ...extra }); await load(); setFeedback(`Status ${value.replaceAll("_", " ")} হয়েছে।`); } catch (error) { setFeedback(error instanceof Error ? error.message : "Status update হয়নি।"); } finally { setSaving(false); } }

  const uploadTargets = useMemo(() => [
    ...lists.map((item) => ({ value: `shopping_list:${item.id}`, label: `Shopping · ${item.title}` })),
    ...bills.map((item) => ({ value: `bill:${item.id}`, label: `Bill · ${item.title}` })),
    ...maintenance.map((item) => ({ value: `maintenance:${item.id}`, label: `Maintenance · ${item.title}` })),
  ], [bills, lists, maintenance]);
  async function upload() { if (!uploadFile || !uploadForm.target) { setFeedback("File ও linked record নির্বাচন করুন।"); return; } const [entityType, entityId] = uploadForm.target.split(":"); const body = new FormData(); body.set("file", uploadFile); body.set("entityType", entityType); body.set("entityId", entityId); body.set("documentType", uploadForm.documentType || "other"); body.set("title", uploadForm.title || uploadFile.name); setSaving(true); try { const response = await fetch("/api/household/upload", { method: "POST", body }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Upload হয়নি।"); setUploadOpen(false); setUploadFile(null); setUploadForm({ documentType: "receipt" }); await load(); setFeedback("Document vault-এ save হয়েছে।"); } catch (error) { setFeedback(error instanceof Error ? error.message : "Upload হয়নি।"); } finally { setSaving(false); } }

  async function exportXlsx() {
    setExporting(true); try {
      const XLSX = await import("xlsx"), workbook = XLSX.utils.book_new(); const add = (name: string, rows: Array<Record<string, unknown>>) => XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), name);
      add("Households", households.map((item) => ({ Name: item.name, Address: item.address ?? "", City: item.city ?? "", Status: item.status, Notes: item.notes ?? "" })));
      add("Shopping Lists", lists.map((item) => ({ Household: householdName(item.household_id), List: item.title, Budget: n(item.budget_amount), "Needed by": item.needed_by ?? "", Status: item.status, Creator: item.created_by_name })));
      add("Shopping Items", items.map((item) => ({ List: listName(item.list_id), Item: item.item_name, Category: item.category, Quantity: n(item.quantity), Unit: item.unit, Estimated: n(item.estimated_cost), Actual: n(item.actual_cost), Priority: item.priority, Assigned: item.assigned_to_name ?? "", Status: item.status, Purchased: item.purchased_by_name ?? "" })));
      add("Utility Bills", bills.map((item) => ({ Household: householdName(item.household_id), Bill: item.title, Category: item.category, Provider: item.provider ?? "", Account: item.account_number ?? "", Month: item.billing_month, Amount: n(item.amount), Due: item.due_date, Recurrence: item.recurrence, Status: effectiveBillStatus(item), Method: item.payment_method ?? "", Reference: item.reference ?? "" })));
      add("Tasks", tasks.map((item) => ({ Household: householdName(item.household_id), Task: item.title, Category: item.category, Assigned: item.assigned_to_name ?? "", Due: item.due_at ?? "", Recurrence: item.recurrence, Priority: item.priority, Status: item.status, Completed: item.completed_by_name ?? "" })));
      add("Maintenance", maintenance.map((item) => ({ Household: householdName(item.household_id), Issue: item.title, Category: item.category, Urgency: item.urgency, Estimated: n(item.estimated_cost), Actual: n(item.actual_cost), Vendor: item.assigned_vendor_name ?? "", Schedule: item.scheduled_at ?? "", Status: item.status, Reporter: item.reported_by_name })));
      add("Service Directory", contacts.map((item) => ({ Service: item.service_type, Name: item.name, Phone: item.phone, Alternate: item.alternate_phone ?? "", Rating: n(item.rating), Trusted: item.is_trusted ? "Yes" : "No", Address: item.address ?? "", Status: item.status })));
      add("Documents", documents.map((item) => ({ Title: item.title, Type: item.document_type, Entity: `${item.entity_type}:${item.entity_id}`, File: item.file_name, Uploader: item.uploaded_by_name, Date: item.created_at })));
      XLSX.writeFile(workbook, `${family?.name_en?.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "family"}-shared-household.xlsx`);
    } finally { setExporting(false); }
  }

  useEffect(() => {
    const modelContext = (document as Document & { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext; if (!modelContext?.registerTool) return; const lifecycle = new AbortController();
    void Promise.resolve(modelContext.registerTool({ name: "get_shared_household_summary", title: "Get shared household summary", description: "Read visible household counts, pending shopping items, due utility bills, open tasks and maintenance issues.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute(input: unknown) { if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input as object).length) throw new Error("No input fields are accepted."); return { households: visibleHouseholds.map((item) => item.name), shoppingItemsNeeded: openItems.length, utilityBillsDue: dueBills.length, utilityAmountDue: dueAmount, openTasks: openTasks.length, openMaintenance: openMaintenance.length }; } }, { signal: lifecycle.signal })).catch(() => undefined); return () => lifecycle.abort();
  }, [dueAmount, dueBills.length, openItems.length, openMaintenance.length, openTasks.length, visibleHouseholds]);

  if (loading) return <main className="grid min-h-[calc(100vh-4rem)] place-items-center"><LoaderCircle className="size-7 animate-spin text-primary" /></main>;
  if (setupRequired) return <main className="mx-auto max-w-3xl p-6 md:p-10"><Empty icon={<Users />} title="আগে family setup সম্পন্ন করুন" text="Approved member হওয়ার পর Shared Household ব্যবহার করা যাবে।" action={<Button asChild className="rounded-xl"><a href="/setup">Family setup</a></Button>} /></main>;

  return <main className="mx-auto w-full max-w-[1550px] space-y-5 px-4 py-5 md:px-7 md:py-7">
    <section className="overflow-hidden rounded-3xl bg-[linear-gradient(125deg,#1e3a5f_0%,#0f766e_55%,#9a5b13_100%)] p-5 text-white shadow-xl md:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div className="max-w-2xl"><div className="flex items-center gap-2 text-sm text-cyan-100"><ShieldCheck className="size-4" /> Everyday family operations</div><h1 className="mt-2 text-2xl font-bold tracking-tight md:text-4xl">Shared Household Management</h1><p className="mt-2 text-sm leading-6 text-white/75">বাজার, utility bill, দায়িত্ব, trusted services, maintenance ও receipts—বাসার দৈনন্দিন সব কাজ এক জায়গায়।</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" className="rounded-xl" onClick={() => void exportXlsx()} disabled={exporting}>{exporting ? <LoaderCircle className="size-4 animate-spin" /> : <Download className="size-4" />} সব XLSX</Button><Button variant="secondary" className="rounded-xl" onClick={() => setUploadOpen(true)} disabled={!uploadTargets.length || migrationRequired}><Upload className="size-4" /> Receipt</Button><Button className="rounded-xl bg-cyan-500 text-slate-950 hover:bg-cyan-400" onClick={() => openCreate("item")} disabled={!filteredLists.length || migrationRequired}><ShoppingBasket className="size-4" /> Item যোগ করুন</Button></div></div></section>
    {migrationRequired ? <div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-800 dark:bg-amber-950/35 dark:text-amber-100">Supabase SQL Editor-এ <b>supabase/migrations/20260927_shared_household.sql</b> চালালে Shared Household data সক্রিয় হবে।</div> : null}
    {feedback ? <div className="flex items-start justify-between gap-3 rounded-2xl border bg-card px-4 py-3 text-sm"><span>{feedback}</span><Button size="icon-xs" variant="ghost" onClick={() => setFeedback(null)}><X /></Button></div> : null}
    <section className="flex flex-col justify-between gap-3 rounded-2xl border bg-card p-4 sm:flex-row sm:items-center"><div><p className="font-semibold">Household filter</p><p className="text-xs text-muted-foreground">নির্দিষ্ট বাসা অথবা পুরো family operation দেখুন</p></div><div className="flex flex-wrap gap-2"><Native value={selectedHousehold} onChange={setSelectedHousehold} options={[["all", "সব Household"], ...visibleHouseholds.map((item) => [item.id, item.name])]} />{canManage ? <Button className="rounded-xl" onClick={() => openCreate("household")} disabled={migrationRequired}><HousePlus /> Household</Button> : null}</div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<ShoppingBasket />} label="Shopping needed" value={String(openItems.length)} note={`${filteredLists.filter((item) => item.status === "active").length} active lists`} tone="cyan" /><Metric icon={<Zap />} label="Utility due" value={money.format(dueAmount)} note={`${dueBills.length} pending or overdue`} tone="amber" /><Metric icon={<ClipboardCheck />} label="Open tasks" value={String(openTasks.length)} note={`${openTasks.filter((item) => item.priority === "urgent").length} urgent`} tone="blue" /><Metric icon={<Wrench />} label="Maintenance" value={String(openMaintenance.length)} note={`${openMaintenance.filter((item) => item.urgency === "critical").length} critical`} tone="rose" /></section>

    <Tabs defaultValue="shopping" className="space-y-4"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-2xl bg-muted/70 p-1"><TabsTrigger value="shopping">Shopping</TabsTrigger><TabsTrigger value="bills">Bills</TabsTrigger><TabsTrigger value="tasks">Tasks</TabsTrigger><TabsTrigger value="maintenance">Maintenance</TabsTrigger><TabsTrigger value="services">Services</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger></TabsList>
      <TabsContent value="shopping"><Section title="Shared shopping lists" description="Real-time প্রয়োজন, assignment, budget ও purchased cost" action={<div className="flex gap-2"><Button variant="outline" className="rounded-xl" onClick={() => openCreate("list")} disabled={!visibleHouseholds.length || migrationRequired}><Plus /> List</Button><Button className="rounded-xl" onClick={() => openCreate("item")} disabled={!filteredLists.length || migrationRequired}><Plus /> Item</Button></div>}><div className="grid gap-4 p-4 xl:grid-cols-2">{filteredLists.map((list) => <ShoppingListCard key={list.id} list={list} items={items.filter((item) => item.list_id === list.id)} household={householdName(list.household_id)} saving={saving} onAdd={() => openCreate("item", { listId: list.id })} onListStatus={(value) => void status("list", list.id, value)} onItemStatus={(item, value) => { if (value === "purchased") { const actualCost = window.prompt("Actual cost", String(n(item.estimated_cost))); if (actualCost === null) return; void status("item", item.id, value, { actualCost }); } else void status("item", item.id, value); }} />)}{!filteredLists.length ? <div className="xl:col-span-2"><Empty icon={<ShoppingBasket />} title="Shopping list নেই" text="সাপ্তাহিক বাজার, medicine অথবা household supplies-এর list তৈরি করুন।" /></div> : null}</div></Section></TabsContent>
      <TabsContent value="bills"><Section title="Utility bills & reminders" description="Due date, recurrence, overdue alert ও payment history" action={canManage ? <Button className="rounded-xl" onClick={() => openCreate("bill")} disabled={!visibleHouseholds.length || migrationRequired}><Plus /> Bill</Button> : undefined}><TableBox><Table><TableHeader><TableRow><TableHead>Due</TableHead><TableHead>Bill</TableHead><TableHead>Household</TableHead><TableHead>Amount</TableHead><TableHead>Recurrence</TableHead><TableHead>Status</TableHead>{canManage ? <TableHead /> : null}</TableRow></TableHeader><TableBody>{filteredBills.map((bill) => <TableRow key={bill.id}><TableCell className={effectiveBillStatus(bill) === "overdue" ? "font-bold text-destructive" : ""}>{date.format(new Date(bill.due_date))}</TableCell><TableCell><p className="font-semibold">{bill.title}</p><p className="text-xs text-muted-foreground">{bill.provider || bill.category}{bill.account_number ? ` · ${bill.account_number}` : ""}</p></TableCell><TableCell>{householdName(bill.household_id)}</TableCell><TableCell className="font-bold">{money.format(n(bill.amount))}</TableCell><TableCell className="capitalize">{bill.recurrence}</TableCell><TableCell><Status value={effectiveBillStatus(bill)} /></TableCell>{canManage ? <TableCell><Menu disabled={saving} items={bill.status === "paid" ? [] : [["Mark paid", () => { const paymentMethod = window.prompt("Payment method: cash / bank / mobile / card / other", bill.payment_method ?? "mobile"); if (paymentMethod === null) return; const reference = window.prompt("Payment reference", bill.reference ?? "") ?? ""; void status("bill", bill.id, "paid", { reference, paymentMethod }); }], ["Skip", () => void status("bill", bill.id, "skipped")]]} /></TableCell> : null}</TableRow>)}<EmptyRows show={!filteredBills.length} columns={canManage ? 7 : 6} /></TableBody></Table></TableBox></Section></TabsContent>
      <TabsContent value="tasks"><Section title="Shared task board" description="Assignment, deadline, recurrence এবং completion" action={<Button className="rounded-xl" onClick={() => openCreate("task")} disabled={!visibleHouseholds.length || migrationRequired}><Plus /> Task</Button>}><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{filteredTasks.map((task) => <TaskCard key={task.id} task={task} household={householdName(task.household_id)} saving={saving} onStatus={(value) => void status("task", task.id, value)} />)}{!filteredTasks.length ? <div className="md:col-span-2 xl:col-span-3"><Empty icon={<ListChecks />} title="Shared task নেই" text="বাজার, cleaning, cooking, care বা bill payment দায়িত্ব দিন।" /></div> : null}</div></Section></TabsContent>
      <TabsContent value="maintenance"><Section title="Maintenance control" description="Issue report, approval, vendor, schedule এবং actual cost" action={<Button className="rounded-xl" onClick={() => openCreate("maintenance")} disabled={!visibleHouseholds.length || migrationRequired}><Plus /> Report issue</Button>}><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{filteredMaintenance.map((request) => <MaintenanceCard key={request.id} request={request} household={householdName(request.household_id)} canManage={canManage} saving={saving} onStatus={(value, extra) => void status("maintenance", request.id, value, extra)} />)}{!filteredMaintenance.length ? <div className="md:col-span-2 xl:col-span-3"><Empty icon={<Wrench />} title="Maintenance issue নেই" text="Electrical, plumbing, appliance বা building সমস্যা report করুন।" /></div> : null}</div></Section></TabsContent>
      <TabsContent value="services"><Section title="Trusted service directory" description="Electrician, plumber, driver, cleaner ও caregiver contacts" action={canManage ? <Button className="rounded-xl" onClick={() => openCreate("contact")} disabled={migrationRequired}><Plus /> Contact</Button> : undefined}><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{contacts.filter((item) => selectedHousehold === "all" || !item.household_id || item.household_id === selectedHousehold).map((contact) => <article key={contact.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Settings2 className="size-5" /></span><div className="flex gap-2">{contact.is_trusted ? <Badge className="gap-1"><BadgeCheck className="size-3" /> Trusted</Badge> : null}<Status value={contact.status} />{canManage ? <Menu disabled={saving} items={contact.status === "active" ? [["Deactivate", () => void status("contact", contact.id, "inactive")]] : [["Activate", () => void status("contact", contact.id, "active")]]} /> : null}</div></div><h3 className="mt-3 font-bold">{contact.name}</h3><p className="text-sm capitalize text-muted-foreground">{contact.service_type}</p><a className="mt-3 flex items-center gap-2 text-sm font-semibold text-primary" href={`tel:${contact.phone}`}><Phone className="size-4" /> {contact.phone}</a><p className="mt-2 flex items-center gap-1 text-xs text-amber-600"><Star className="size-3 fill-current" /> {n(contact.rating).toFixed(1)} / 5</p></article>)}{!contacts.length ? <div className="md:col-span-2 xl:col-span-3"><Empty icon={<Phone />} title="Service contact নেই" text="বিশ্বস্ত service provider যোগ করুন।" /></div> : null}</div></Section></TabsContent>
      <TabsContent value="documents"><Section title="Household receipt vault" description="Shopping receipt, bill invoice, warranty ও maintenance quotation" action={<Button className="rounded-xl" onClick={() => setUploadOpen(true)} disabled={!uploadTargets.length || migrationRequired}><Upload /> Upload</Button>}><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{documents.map((document) => <a key={document.id} href={`/api/household-document/${document.id}`} target="_blank" rel="noreferrer" className="rounded-2xl border p-4 transition hover:border-primary/40 hover:bg-muted/30"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><FileText className="size-5" /></span><p className="mt-3 font-semibold">{document.title}</p><p className="mt-1 truncate text-xs text-muted-foreground">{document.file_name}</p><p className="mt-3 text-xs text-muted-foreground">{document.document_type} · {document.uploaded_by_name} · {date.format(new Date(document.created_at))}</p></a>)}{!documents.length ? <div className="md:col-span-2 xl:col-span-3"><Empty icon={<ReceiptText />} title="Document নেই" text="Receipt, invoice, warranty বা quotation upload করুন।" /></div> : null}</div></Section></TabsContent>
    </Tabs>

    <Dialog open={Boolean(kind)} onOpenChange={(open) => !open && setKind(null)}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-2xl"><DialogHeader><DialogTitle>{kind ? titles[kind] : "নতুন record"}</DialogTitle><DialogDescription>Household operation-এর প্রয়োজনীয় তথ্য দিন।</DialogDescription></DialogHeader>{kind ? <CreateForm kind={kind} form={form} setForm={setForm} households={visibleHouseholds} lists={lists.filter((item) => item.status === "active")} contacts={contacts.filter((item) => item.status === "active")} canManage={canManage} /> : null}<DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => setKind(null)}>বাতিল</Button><Button className="rounded-xl" onClick={() => void create()} disabled={saving}>{saving ? <LoaderCircle className="size-4 animate-spin" /> : <CheckCircle2 className="size-4" />} Save</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={uploadOpen} onOpenChange={setUploadOpen}><DialogContent className="rounded-3xl sm:max-w-xl"><DialogHeader><DialogTitle>Household document upload</DialogTitle><DialogDescription>JPG, PNG, WebP, PDF বা Word; সর্বোচ্চ ১২ MB।</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="Linked record"><Native value={uploadForm.target ?? ""} onChange={(value) => setUploadForm((old) => ({ ...old, target: value }))} options={uploadTargets.map((item) => [item.value, item.label])} placeholder="Record নির্বাচন করুন" /></Field><Field label="Type"><Native value={uploadForm.documentType} onChange={(value) => setUploadForm((old) => ({ ...old, documentType: value }))} options={[["receipt", "Receipt"], ["invoice", "Invoice"], ["warranty", "Warranty"], ["quotation", "Quotation"], ["other", "Other"]]} /></Field><Field label="Title"><Input value={uploadForm.title ?? ""} onChange={(event) => setUploadForm((old) => ({ ...old, title: event.target.value }))} /></Field><Field label="File"><Input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx" onChange={(event) => setUploadFile(event.target.files?.[0] ?? null)} /></Field></div><DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => setUploadOpen(false)}>বাতিল</Button><Button className="rounded-xl" onClick={() => void upload()} disabled={saving || !uploadFile}><Upload /> Upload</Button></DialogFooter></DialogContent></Dialog>
  </main>;
}

function CreateForm({ kind, form, setForm, households, lists, contacts, canManage }: { kind: Kind; form: Form; setForm: (form: Form) => void; households: Household[]; lists: ShoppingList[]; contacts: ServiceContact[]; canManage: boolean }) {
  const set = (key: string, value: string) => setForm({ ...form, [key]: value });
  const input = (key: string, label: string, type = "text", props: Record<string, string> = {}) => <Field label={label}><Input type={type} value={form[key] ?? ""} onChange={(event) => set(key, event.target.value)} {...props} /></Field>;
  const select = (key: string, label: string, options: string[][], placeholder?: string) => <Field label={label}><Native value={form[key]} onChange={(value) => set(key, value)} options={options} placeholder={placeholder} /></Field>;
  const household = select("householdId", "Household", households.map((item) => [item.id, item.name]), "Household নির্বাচন করুন");
  const notes = <Field label={kind === "maintenance" ? "সমস্যার বিস্তারিত" : "Notes"}><Textarea rows={4} value={form[kind === "maintenance" ? "description" : "notes"] ?? ""} onChange={(event) => set(kind === "maintenance" ? "description" : "notes", event.target.value)} /></Field>;
  if (kind === "household") return <div className="grid gap-4 py-2 sm:grid-cols-2">{input("name", "Household name")}{input("city", "City")}{input("address", "Address")}<div className="sm:col-span-2">{notes}</div></div>;
  if (kind === "list") return <div className="grid gap-4 py-2 sm:grid-cols-2">{household}{input("title", "List title")}{input("budgetAmount", "Budget", "number", { min: "0" })}{input("neededBy", "Needed by", "date")}<div className="sm:col-span-2">{input("description", "Description")}</div></div>;
  if (kind === "item") return <div className="grid gap-4 py-2 sm:grid-cols-2">{select("listId", "Shopping list", lists.map((item) => [item.id, item.title]), "List নির্বাচন করুন")}{input("itemName", "Item name")}{select("category", "Category", [["grocery", "Grocery"], ["medicine", "Medicine"], ["household", "Household"], ["baby", "Baby"], ["personal", "Personal"], ["other", "Other"]])}{input("quantity", "Quantity", "number", { min: "0.01" })}{input("unit", "Unit")}{input("estimatedCost", "Estimated cost", "number", { min: "0" })}{select("priority", "Priority", priorityOptions)}{input("assignedToName", "Assigned to")}<div className="sm:col-span-2">{notes}</div></div>;
  if (kind === "bill") return <div className="grid gap-4 py-2 sm:grid-cols-2">{household}{input("title", "Bill title")}{select("category", "Category", [["electricity", "Electricity"], ["gas", "Gas"], ["water", "Water"], ["internet", "Internet"], ["phone", "Phone"], ["rent", "Rent"], ["maintenance", "Maintenance"], ["other", "Other"]])}{input("provider", "Provider")}{input("accountNumber", "Account / meter number")}{input("billingMonth", "Billing month", "date")}{input("amount", "Amount", "number", { min: "1" })}{input("dueDate", "Due date", "date")}{select("recurrence", "Recurrence", [["none", "None"], ["monthly", "Monthly"], ["quarterly", "Quarterly"], ["yearly", "Yearly"]])}<div className="sm:col-span-2">{notes}</div></div>;
  if (kind === "task") return <div className="grid gap-4 py-2 sm:grid-cols-2">{household}{input("title", "Task title")}{select("category", "Category", [["cleaning", "Cleaning"], ["cooking", "Cooking"], ["shopping", "Shopping"], ["care", "Care"], ["repair", "Repair"], ["bill", "Bill"], ["other", "Other"]])}{input("assignedToName", "Assigned to")}{input("dueAt", "Due time", "datetime-local")}{select("recurrence", "Recurrence", [["none", "None"], ["daily", "Daily"], ["weekly", "Weekly"], ["monthly", "Monthly"]])}{select("priority", "Priority", priorityOptions)}<div className="sm:col-span-2">{notes}</div></div>;
  if (kind === "contact") return <div className="grid gap-4 py-2 sm:grid-cols-2">{household}{input("name", "Service person / company")}{select("serviceType", "Service", [["electrician", "Electrician"], ["plumber", "Plumber"], ["cleaner", "Cleaner"], ["driver", "Driver"], ["technician", "Technician"], ["caregiver", "Caregiver"], ["security", "Security"], ["other", "Other"]])}{input("phone", "Phone", "tel")}{input("alternatePhone", "Alternate phone", "tel")}{input("rating", "Rating 0-5", "number", { min: "0", max: "5", step: "0.5" })}{canManage ? select("isTrusted", "Trust status", [["false", "Normal contact"], ["true", "Trusted / verified"]]) : null}{input("address", "Address")}<div className="sm:col-span-2">{notes}</div></div>;
  return <div className="grid gap-4 py-2 sm:grid-cols-2">{household}{input("title", "Issue title")}{select("category", "Category", [["electrical", "Electrical"], ["plumbing", "Plumbing"], ["appliance", "Appliance"], ["building", "Building"], ["cleaning", "Cleaning"], ["security", "Security"], ["other", "Other"]])}{select("urgency", "Urgency", [["normal", "Normal"], ["high", "High"], ["critical", "Critical"]])}{input("estimatedCost", "Estimated cost", "number", { min: "0" })}{select("serviceContactId", "Service contact", contacts.map((item) => [item.id, `${item.name} · ${item.service_type}`]), "Optional")}{input("assignedVendorName", "Vendor name")}{input("scheduledAt", "Schedule", "datetime-local")}<div className="sm:col-span-2">{notes}</div></div>;
}

const priorityOptions = [["low", "Low"], ["normal", "Normal"], ["high", "High"], ["urgent", "Urgent"]];
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
function Native({ value, onChange, options, placeholder }: { value?: string; onChange: (value: string) => void; options: string[][]; placeholder?: string }) { return <select value={value ?? ""} onChange={(event) => onChange(event.target.value)} className="h-10 min-w-48 rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15">{placeholder ? <option value="">{placeholder}</option> : null}{options.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select>; }
function effectiveBillStatus(bill: UtilityBill) { return bill.status === "pending" && new Date(`${bill.due_date}T23:59:59`).getTime() < Date.now() ? "overdue" : bill.status; }
function Metric({ icon, label, value, note, tone }: { icon: ReactNode; label: string; value: string; note: string; tone: "cyan" | "amber" | "blue" | "rose" }) { const colors = { cyan: "bg-cyan-500/10 text-cyan-700 dark:text-cyan-300", amber: "bg-amber-500/10 text-amber-700 dark:text-amber-300", blue: "bg-blue-500/10 text-blue-700 dark:text-blue-300", rose: "bg-rose-500/10 text-rose-700 dark:text-rose-300" }; return <Card className="rounded-2xl shadow-none"><CardContent className="flex items-start gap-4 p-5"><span className={`grid size-11 shrink-0 place-items-center rounded-2xl ${colors[tone]}`}>{icon}</span><div className="min-w-0"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 truncate text-2xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div></CardContent></Card>; }
function Section({ title, description, action, children }: { title: string; description: string; action?: ReactNode; children: ReactNode }) { return <Card className="overflow-hidden rounded-3xl py-0 shadow-none"><CardHeader className="flex-row items-start justify-between gap-4 border-b p-5 md:p-6"><div><CardTitle>{title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{action}</CardHeader><CardContent className="p-0">{children}</CardContent></Card>; }
function TableBox({ children }: { children: ReactNode }) { return <div className="overflow-x-auto">{children}</div>; }
function Status({ value }: { value: string }) { const good = ["active", "paid", "completed", "purchased"]; const bad = ["overdue", "cancelled", "unavailable", "inactive", "archived"]; return <Badge variant={bad.includes(value) ? "destructive" : good.includes(value) ? "secondary" : "outline"} className="capitalize">{value.replaceAll("_", " ")}</Badge>; }
function Menu({ items, disabled }: { items: Array<[string, () => void]>; disabled: boolean }) { if (!items.length) return null; return <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon-sm" variant="ghost" disabled={disabled}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{items.map(([label, run]) => <DropdownMenuItem key={label} onClick={run}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>; }
function EmptyRows({ show, columns }: { show: boolean; columns: number }) { return show ? <TableRow><TableCell colSpan={columns} className="h-32 text-center text-muted-foreground">এখনও কোনো record নেই।</TableCell></TableRow> : null; }
function Empty({ icon, title, text, action }: { icon: ReactNode; title: string; text: string; action?: ReactNode }) { return <div className="flex min-h-52 flex-col items-center justify-center p-6 text-center"><span className="text-muted-foreground/50">{icon}</span><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 max-w-md text-sm text-muted-foreground">{text}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
function ShoppingListCard({ list, items, household, saving, onAdd, onListStatus, onItemStatus }: { list: ShoppingList; items: ShoppingItem[]; household: string; saving: boolean; onAdd: () => void; onListStatus: (value: string) => void; onItemStatus: (item: ShoppingItem, value: string) => void }) { const purchased = items.filter((item) => item.status === "purchased"); const spent = purchased.reduce((sum, item) => sum + n(item.actual_cost), 0); const estimate = items.reduce((sum, item) => sum + n(item.estimated_cost), 0); const progress = items.length ? purchased.length / items.length * 100 : 0; return <article className="overflow-hidden rounded-2xl border"><div className="border-b bg-muted/20 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Status value={list.status} /><Badge variant="outline">{household}</Badge></div><h3 className="mt-2 text-lg font-bold">{list.title}</h3></div><div className="flex"><Button size="sm" variant="outline" className="rounded-xl" onClick={onAdd}><Plus /> Item</Button><Menu disabled={saving} items={list.status === "active" ? [["Complete list", () => onListStatus("completed")], ["Archive", () => onListStatus("archived")]] : [["Reopen", () => onListStatus("active")]]} /></div></div><Progress value={progress} className="mt-4" /><div className="mt-2 flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>{purchased.length}/{items.length} purchased</span><span>{money.format(spent)} actual · {money.format(estimate)} estimated · {money.format(n(list.budget_amount))} budget</span></div></div><div className="divide-y">{items.map((item) => <div key={item.id} className="flex items-center gap-3 p-3"><button type="button" onClick={() => onItemStatus(item, item.status === "purchased" ? "needed" : "purchased")} className={`grid size-8 shrink-0 place-items-center rounded-full border ${item.status === "purchased" ? "border-emerald-500 bg-emerald-500 text-white" : "border-border"}`}><CheckCircle2 className="size-4" /></button><div className="min-w-0 flex-1"><p className={`font-semibold ${item.status === "purchased" ? "text-muted-foreground line-through" : ""}`}>{item.item_name}</p><p className="text-xs text-muted-foreground">{n(item.quantity)} {item.unit} · {item.assigned_to_name || "Unassigned"}</p></div><div className="text-right"><p className="text-sm font-semibold">{money.format(item.status === "purchased" ? n(item.actual_cost) : n(item.estimated_cost))}</p><Badge variant={item.priority === "urgent" ? "destructive" : "outline"}>{item.priority}</Badge></div><Menu disabled={saving} items={item.status === "needed" ? [["Unavailable", () => onItemStatus(item, "unavailable")], ["Cancel", () => onItemStatus(item, "cancelled")]] : [["Needed again", () => onItemStatus(item, "needed")]]} /></div>)}{!items.length ? <p className="p-6 text-center text-sm text-muted-foreground">Item যোগ করলে list এখানে দেখা যাবে।</p> : null}</div></article>; }
function TaskCard({ task, household, saving, onStatus }: { task: HouseholdTask; household: string; saving: boolean; onStatus: (value: string) => void }) { return <article className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><Status value={task.status} /><Badge variant={task.priority === "urgent" ? "destructive" : "outline"}>{task.priority}</Badge></div><Menu disabled={saving} items={task.status === "todo" ? [["Start", () => onStatus("in_progress")], ["Complete", () => onStatus("completed")], ["Cancel", () => onStatus("cancelled")]] : task.status === "in_progress" ? [["Complete", () => onStatus("completed")], ["Back to todo", () => onStatus("todo")]] : [["Reopen", () => onStatus("todo")]]} /></div><h3 className="mt-3 font-bold">{task.title}</h3><p className="mt-1 text-sm text-muted-foreground">{household} · {task.category}</p><div className="mt-3 rounded-xl bg-muted/45 p-3 text-sm"><p><b>Assigned:</b> {task.assigned_to_name || "Anyone"}</p><p className="mt-1"><b>Due:</b> {task.due_at ? dateTime.format(new Date(task.due_at)) : "No deadline"}</p><p className="mt-1"><b>Repeats:</b> {task.recurrence}</p></div></article>; }
function MaintenanceCard({ request, household, canManage, saving, onStatus }: { request: MaintenanceRequest; household: string; canManage: boolean; saving: boolean; onStatus: (value: string, extra?: Record<string, unknown>) => void }) { const manage = (value: string) => { const actualCost = value === "completed" ? window.prompt("Actual cost", String(n(request.actual_cost) || n(request.estimated_cost))) : null; const vendor = ["approved", "scheduled", "in_progress"].includes(value) ? window.prompt("Vendor / service person", request.assigned_vendor_name ?? "") : null; const scheduledAt = value === "scheduled" ? window.prompt("Schedule (example: 2026-09-28T10:00)", request.scheduled_at?.slice(0, 16) ?? "") : null; onStatus(value, { actualCost: actualCost ?? undefined, assignedVendorName: vendor ?? undefined, scheduledAt: scheduledAt ?? undefined }); }; const items: Array<[string, () => void]> = canManage ? request.status === "reported" ? [["Approve", () => manage("approved")], ["Cancel", () => manage("cancelled")]] : request.status === "approved" ? [["Schedule", () => manage("scheduled")], ["Start", () => manage("in_progress")]] : ["scheduled", "in_progress"].includes(request.status) ? [["Complete", () => manage("completed")]] : [] : request.status === "reported" ? [["Cancel", () => onStatus("cancelled")]] : []; return <article className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><Badge variant={request.urgency === "critical" ? "destructive" : "secondary"}>{request.urgency}</Badge><Status value={request.status} /></div><Menu disabled={saving} items={items} /></div><h3 className="mt-3 font-bold">{request.title}</h3><p className="mt-1 text-xs text-muted-foreground">{household} · {request.category} · by {request.reported_by_name}</p><p className="mt-3 line-clamp-3 text-sm text-muted-foreground">{request.description}</p><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl bg-muted/45 p-3"><p className="text-xs text-muted-foreground">Estimated</p><p className="font-bold">{money.format(n(request.estimated_cost))}</p></div><div className="rounded-xl bg-muted/45 p-3"><p className="text-xs text-muted-foreground">Actual</p><p className="font-bold">{money.format(n(request.actual_cost))}</p></div></div>{request.assigned_vendor_name ? <p className="mt-3 text-xs text-muted-foreground">Vendor: {request.assigned_vendor_name}</p> : null}</article>; }
